window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"C1-001","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電力系統架構","level":"2理解","question":"下列何者最符合教材對現代電力系統潮流方向的說明？","option_a":"電力永遠只能由大型電廠單向流向用戶","option_b":"分散式與再生能源可能直接併入配電端或用戶端，使潮流不一定只有由上而下","option_c":"再生能源只能接在345kV輸電端","option_d":"配電系統不可能有電力回送","answer":"B","explanation":"傳統大型機組多由高壓輸電往下供應，但分散式與再生能源可能在配電或用戶端併網，因此潮流可呈現雙向或由下往上。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"電力系統架構","is_active":true,"tags":"單元01;易混淆;理解"},
{"id":"C1-002","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜備用與備轉","level":"3情境","question":"主管正在檢視明年度尖峰期間是否有足夠發電能力；值班員則在關心今天此刻還有多少可調度裕度。兩者應分別優先看哪個指標？","option_a":"前者備轉容量率、後者備用容量率","option_b":"兩者都只看備用容量率","option_c":"前者備用容量率、後者備轉容量率","option_d":"兩者都只看備轉容量率","answer":"C","explanation":"備用容量率偏遠期與年度供電充裕；備轉容量率反映短期、當日實際可調度裕度。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"備用容量與備轉容量","is_active":true,"tags":"單元01;易混淆;備用容量;備轉容量"},
{"id":"C1-003","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜備轉容量計算","level":"3情境計算","question":"某日系統運轉淨尖峰能力40,000MW、瞬時尖峰負載36,000MW。若有人用40,000MW當分母算備轉容量率，哪個敘述正確？","option_a":"算法正確，結果10%","option_b":"分母應為瞬時尖峰負載36,000MW，正確值約11.1%","option_c":"分母應為備轉容量4,000MW，正確值100%","option_d":"備轉容量率不需要分母","answer":"B","explanation":"備轉容量率＝(運轉淨尖峰能力－瞬時尖峰負載)÷瞬時尖峰負載×100%。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"備轉容量率公式","is_active":true,"tags":"單元01;易混淆;計算;備轉容量率"},
{"id":"C1-004","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電網結構","level":"2理解","question":"下列哪一組最接近教材所稱的「電網結構」設備，而非「電源結構」？","option_a":"核能、燃煤、水力、風力","option_b":"輸電線路、變壓器、電容器、電抗器、保護電驛","option_c":"燃料槽、鍋爐、汽輪機、發電機","option_d":"太陽能、地熱、生質能、沼氣","answer":"B","explanation":"教材將輸電線路、變壓器、電容器、電抗器、保護電驛等歸為電網結構。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"電力系統之電源結構與電網結構","is_active":true,"tags":"單元01;易混淆;電網結構"},
{"id":"C1-005","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜負載限制","level":"3情境","question":"已預測明日供電可能不足，且可事前安排用戶減少用電；另一情況則是機組突然故障、必須立即限電。兩者分別較接近何者？","option_a":"緊急負載限制／計畫性負載限制","option_b":"計畫性負載限制／緊急負載限制","option_c":"兩者皆為計畫性負載限制","option_d":"兩者皆為緊急負載限制","answer":"B","explanation":"可預先掌握並安排者較屬計畫性負載限制；突發事故需立即因應者屬緊急負載限制。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"負載限制與緊急應變","is_active":true,"tags":"單元01;易混淆;情境;負載限制"},
{"id":"C1-006","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜可靠度指標","level":"2理解","question":"若題目問「遠期發電端供電可靠度」與「短期可調度容量裕度」，最容易混淆的正確配對為何？","option_a":"前者備轉容量率、後者備用容量率","option_b":"前者備用容量率、後者備轉容量率","option_c":"兩者皆為線路損失率","option_d":"兩者皆為每戶停電時間","answer":"B","explanation":"備用容量率偏遠期供電可靠度；備轉容量率偏短期實際可調度裕度。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"可靠度指標","is_active":true,"tags":"單元01;易混淆;可靠度"},

{"id":"C2-001","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜電源與電網調度","level":"3情境","question":"下列哪一組較符合教材對電源調度與電網調度的分工？","option_a":"電源調度管電壓與潮流；電網調度管頻率與備轉","option_b":"電源調度管頻率、發電資源與備轉；電網調度管電壓、網路操作與潮流","option_c":"兩者都只做負載預測","option_d":"兩者都只管理電價","answer":"B","explanation":"電源調度偏頻率、發電資源與備轉；電網調度偏電壓、輸電網操作及潮流監控。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"電力調度任務與結語","is_active":true,"tags":"單元02;易混淆;電源調度;電網調度"},
{"id":"C2-002","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜負載預測","level":"2理解","question":"下列哪個因素若出現在選項中，最應優先歸類為短期負載影響因素？","option_a":"人口結構","option_b":"產業結構","option_c":"特殊節日與氣溫","option_d":"家電長期普及率","answer":"C","explanation":"教材把氣溫、特殊節日、生活習慣及生產活動列為短期因素；人口、所得、產業結構等偏長期。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"影響系統負載因素","is_active":true,"tags":"單元02;易混淆;負載預測"},
{"id":"C2-003","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜日負載曲線","level":"3情境","question":"某敘述稱「台灣一般工作日只有中午單一尖峰，深夜負載最高」。依教材判斷應如何修正？","option_a":"完全正確","option_b":"通常白天與夜間有雙尖峰，深夜較低，工作日中午因午休負載變化較明顯","option_c":"只有凌晨有尖峰","option_d":"日負載全天固定不變","answer":"B","explanation":"教材指出白天與夜間形成雙尖峰，深夜最低；工作日中午因午休有較明顯變化。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"台灣電力系統負載特性","is_active":true,"tags":"單元02;易混淆;負載曲線"},
{"id":"C2-004","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜調度流程","level":"3情境","question":"下列哪個流程最符合教材的調度邏輯？","option_a":"先完全忽略負載預測，當天才決定所有發電計畫","option_b":"先依負載預測安排發電計畫，調度當日再依即時負載與機組狀況調整","option_c":"只依年度GDP決定當日出力","option_d":"所有機組固定輸出不需調整","answer":"B","explanation":"負載預測提供事前發電計畫基礎，調度日再依即時負載與機組狀況進行調整。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"電源調度之任務","is_active":true,"tags":"單元02;易混淆;調度流程"},
{"id":"C2-005","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜機組角色","level":"2理解","question":"若題目描述「可較快速啟停、用來因應尖峰需求」，最可能是哪一類機組？","option_a":"基載機組","option_b":"尖載機組","option_c":"長期備用容量","option_d":"輸電設備","answer":"B","explanation":"尖載機組具較快啟停與反應能力，典型可包括水力、燃油或燃氣等。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"機組調度原則","is_active":true,"tags":"單元02;易混淆;機組角色"},
{"id":"C2-006","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜共同最佳化","level":"3情境","question":"共同最佳化（Co-Optimize）不是單純選最便宜機組，而要同時考量機組與系統限制。其核心目標最接近何者？","option_a":"在限制條件下最小化全系統發電成本","option_b":"最大化所有機組出力","option_c":"讓所有機組同時啟動","option_d":"固定每個節點相同出力","answer":"A","explanation":"教材的目標函數為Min{全系統發電成本}，同時考量機組與系統限制。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"電力市場之共同最佳化","is_active":true,"tags":"單元02;易混淆;共同最佳化"},

{"id":"C3-001","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜市場類型","level":"3情境","question":"某市場主要目的是降低長期價格波動、鼓勵發電投資，交易的是較遠期容量。這最接近哪一市場？","option_a":"電能批發市場","option_b":"容量市場","option_c":"零售市場","option_d":"即時輔助服務","answer":"B","explanation":"容量市場著重遠期容量與投資誘因，並可降低市場價格波動。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力市場架構－容量市場","is_active":true,"tags":"單元03;易混淆;容量市場"},
{"id":"C3-002","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜市場類型","level":"3情境","question":"若重點是「確保電能、電壓、頻率平衡與穩定」，最直接對應哪一類市場？","option_a":"零售市場","option_b":"容量市場","option_c":"輔助服務市場","option_d":"燃料市場","answer":"C","explanation":"輔助服務市場的目的在即時調度前確保電能、電壓與頻率之平衡與穩定。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力市場架構－輔助服務市場","is_active":true,"tags":"單元03;易混淆;輔助服務市場"},
{"id":"C3-003","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜日前與即時市場","level":"2理解","question":"下列哪一組對日前市場與即時市場的描述較正確？","option_a":"日前市場在運轉前一日安排交易；即時市場處理調度日即時需求","option_b":"日前市場只交易十年後容量；即時市場只做帳務","option_c":"兩者都只做零售售電","option_d":"兩者都與調度無關","answer":"A","explanation":"日前市場處理運轉前一日的交易安排，即時市場則用於調度日的即時需求。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"市場時間尺度與國內市場架構","is_active":true,"tags":"單元03;易混淆;日前市場;即時市場"},
{"id":"C3-004","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜平台市場架構","level":"2理解","question":"依教材引用之電力交易平台設置規則，平台主要分為哪兩個市場？","option_a":"日前輔助服務市場與備用容量市場","option_b":"零售市場與期貨市場","option_c":"燃料市場與輸電市場","option_d":"碳權市場與股票市場","answer":"A","explanation":"教材引用規則，電力交易平台分為日前輔助服務市場與備用容量市場。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力交易平台設置規則","is_active":true,"tags":"單元03;易混淆;市場架構"},
{"id":"C3-005","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜管理規範檢討","level":"3情境","question":"除主管機關另有指示外，教材引用規則指出管理規範及作業程序至少多久應檢討一次？","option_a":"每半年","option_b":"每一年","option_c":"每二年","option_d":"每五年","answer":"C","explanation":"教材引用規則說明，原則上至少每二年檢討一次。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力交易平台設置規則第15條","is_active":true,"tags":"單元03;易混淆;期限"},
{"id":"C3-006","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜批發與零售","level":"2理解","question":"下列配對何者正確？","option_a":"電能批發市場－開放用戶自由選擇電力來源；零售市場－促進發電自由競爭","option_b":"電能批發市場－促進發電自由競爭；零售市場－開放用戶自由選擇電力來源","option_c":"兩者都只交易備用容量","option_d":"兩者都只做頻率調整","answer":"B","explanation":"批發市場偏發電自由競爭與效率；零售市場偏用戶選擇電力來源。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力市場架構","is_active":true,"tags":"單元03;易混淆;批發市場;零售市場"},

{"id":"C4-001","subject":"科目一｜電力系統與電力市場","topic":"第4單元｜商品辨識","level":"3情境","question":"某資源要在1秒內以雙向充放電追蹤頻率偏差，最符合哪一商品？","option_a":"dReg","option_b":"sReg","option_c":"即時備轉","option_d":"補充備轉","answer":"A","explanation":"dReg屬動態調頻，反應時間不超過1秒，適合快速雙向調節的資源如併網型儲能。","source_title":"04. 電力交易平台參考資料 輔助服務概論","source_url":"","source_locator":"我國輔助服務項目分類","is_active":true,"tags":"單元04;易混淆;商品辨識"},
{"id":"C4-002","subject":"科目一｜電力系統與電力市場","topic":"第4單元｜商品辨識","level":"3情境","question":"系統遇到機組跳機等偶發事件，需要在10分鐘內補上容量，最符合哪一商品？","option_a":"sReg","option_b":"E-dReg","option_c":"即時備轉","option_d":"補充備轉","answer":"C","explanation":"即時備轉用於機組跳機、淨負載突增等偶發事件，反應時間不超過10分鐘。","source_title":"04. 電力交易平台參考資料 輔助服務概論","source_url":"","source_locator":"我國輔助服務項目分類","is_active":true,"tags":"單元04;易混淆;即時備轉"},
{"id":"C4-003","subject":"科目一｜電力系統與電力市場","topic":"第4單元｜商品辨識","level":"3情境","question":"若重點是因應負載突增與供需預測誤差，並以經濟調度補充額外電能需求，最接近哪一商品？","option_a":"dReg","option_b":"補充備轉","option_c":"E-dReg","option_d":"sReg","answer":"B","explanation":"補充備轉反應時間較長，主要補充負載突增或供需預測誤差造成的額外電能需求。","source_title":"04. 電力交易平台參考資料 輔助服務概論","source_url":"","source_locator":"我國輔助服務項目分類","is_active":true,"tags":"單元04;易混淆;補充備轉"},

{"id":"C5-001","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜專業人員證明","level":"3情境","question":"甲公司以自有資源參與，乙公司以代理其他資源方式參與。依教材附件，兩者所需專業人員資格證明張數分別為何？","option_a":"甲1張、乙3張","option_b":"甲3張、乙1張","option_c":"兩者皆1張","option_d":"兩者皆3張","answer":"A","explanation":"自有資源模式1張；代理資源模式3張。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"附件一 註冊登記程序","is_active":true,"tags":"單元05;易混淆;專業人員"},
{"id":"C5-002","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜保證金與註冊失效","level":"3情境","question":"下列哪一組最容易混淆，但正確？","option_a":"保證金不足收到通知後5個工作日內補足；不足額連續達180日可能被註銷註冊","option_b":"保證金不足180日後才需補足；5日就立即註銷","option_c":"兩個期限皆為30日","option_d":"兩個期限皆為10日","answer":"A","explanation":"5個工作日是補足期限；連續180日則是註冊登記可能失效的條件之一。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第十條保證金規範、第十三條註冊登記失效","is_active":true,"tags":"單元05;易混淆;期限;保證金"},
{"id":"C5-003","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜能力測試與聚合","level":"3情境","question":"日前輔助服務市場某單一資源僅80kW，若欲依教材規定進行能力測試，較適當的作法是？","option_a":"免測試即可參與","option_b":"至少聚合同類型資源達100kW後，視為單一資源進行能力測試","option_c":"只要10kW即可單獨測試","option_d":"改成任何不同類型資源混合即可","answer":"B","explanation":"低於100kW之參與資源，應至少聚合同類型資源達100kW，始得視為單一資源進行能力測試。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第十五條 資源能力測試及聚合","is_active":true,"tags":"單元05;易混淆;100kW;聚合"},
{"id":"C5-004","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜爭議處理","level":"3情境","question":"交易爭議先與電力交易單位協商仍未解決，依教材程序下一步最合理的是？","option_a":"直接永久停權","option_b":"由學者專家協調會進行協調；協調不成再申請電業爭議調處審議會","option_c":"自動由賣方勝訴","option_d":"立即向一般消費爭議機構結案","answer":"B","explanation":"教材列示先協商，仍未解決則由學者專家協調會協調；協調不成時得申請電業爭議調處審議會。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第七章 爭議處理機制","is_active":true,"tags":"單元05;易混淆;爭議處理"},
{"id":"C5-005","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜爭議期限","level":"3情境","question":"依教材，協調委員的選定與召集協調委員的共推，各有一個容易混淆的10日期限。下列何者正確？","option_a":"收到對方名單次日起10日內選出一位；兩位協調委員選定次日起10日內共推召集協調委員","option_b":"兩個期限都為30日","option_c":"前者90日、後者180日","option_d":"均無期限","answer":"A","explanation":"教材第三十六條分別規定兩個10日期限。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第三十六條 學者專家協調會之組成","is_active":true,"tags":"單元05;易混淆;10日;爭議"},
{"id":"C5-006","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜違規處理","level":"3情境","question":"備用容量市場買賣方未依媒合結果締約，教材列示的重大後果之一為何？","option_a":"二年內不得參與備用容量市場，且可能不發還保證金","option_b":"僅增加一次登入驗證","option_c":"自動提高下一次得標順位","option_d":"完全沒有處分","answer":"A","explanation":"特定違反備用容量市場規範情形，二年內不得參與；未依媒合結果締約者並可能不予發還保證金。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第四十條 違反備用容量市場相關管理規範","is_active":true,"tags":"單元05;易混淆;違規;二年"},

{"id":"C6-001","subject":"科目二｜電力交易平台市場規則","topic":"第6單元｜市場角色","level":"3情境","question":"日前輔助服務市場與備用容量市場的買方身分容易混淆，下列何者正確？","option_a":"日前輔助服務市場買方為輸配電業；備用容量市場買方為備用供電容量義務者","option_b":"兩者買方都只能是一般用戶","option_c":"日前市場買方是容量義務者；備用市場買方是儲能設備","option_d":"兩者均無買方","answer":"A","explanation":"日前輔助服務市場由輸配電業作為買方；備用容量市場則由負擔備用供電容量義務者作為買方。","source_title":"06. 電力交易平台參考資料 日前輔助服務市場之參與作法","source_url":"","source_locator":"參與資格－市場總覽","is_active":true,"tags":"單元06;易混淆;買方;市場角色"},
{"id":"C6-002","subject":"科目二｜電力交易平台市場規則","topic":"第6單元｜專業人員資格","level":"3情境","question":"下列哪個敘述最符合教材對「取得專業人員資格證明」的說明？","option_a":"只通過筆試即可直接取得完整資格證明","option_b":"需通過資格測驗，並參與上機訓練；且專業人員應為合格交易者受僱人","option_c":"只要加入LINE群組即可","option_d":"只要持有一般電機證照即可自動取得","answer":"B","explanation":"教材說明申請者須通過資格測驗並參與上機訓練，且專業人員應為合格交易者之受僱人。","source_title":"06. 電力交易平台參考資料 日前輔助服務市場之參與作法","source_url":"","source_locator":"電力交易平台專業人員資格證明","is_active":true,"tags":"單元06;易混淆;資格證明"},
{"id":"C6-003","subject":"科目二｜電力交易平台市場規則","topic":"第6單元｜資格證明張數","level":"2理解","question":"若公司改由自有資源模式轉為代理資源模式，專業人員資格證明最低張數由多少變為多少？","option_a":"1張變3張","option_b":"3張變1張","option_c":"1張變2張","option_d":"完全不變，皆0張","answer":"A","explanation":"教材列示自有資源1張、代理資源3張。","source_title":"06. 電力交易平台參考資料 日前輔助服務市場之參與作法","source_url":"","source_locator":"註冊登記程序－專業人員資格證明","is_active":true,"tags":"單元06;易混淆;自有資源;代理資源"},

{"id":"C7-001","subject":"科目二｜電力交易平台市場規則","topic":"第7單元｜儲能規格","level":"3情境","question":"某併網型儲能欲參與dReg 4MW，依教材其儲能電能量至少應為多少？","option_a":"1MWh","option_b":"2MWh","option_c":"4MWh","option_d":"10MWh","answer":"B","explanation":"dReg儲能電能量至少為參與容量的0.5倍；4MW×0.5＝2MWh。","source_title":"07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格","source_url":"","source_locator":"併網型儲能設備參與dReg","is_active":true,"tags":"單元07;易混淆;計算;dReg;儲能"},
{"id":"C7-002","subject":"科目二｜電力交易平台市場規則","topic":"第7單元｜儲能規格","level":"3情境","question":"某併網型儲能欲參與E-dReg 2MW，依教材最低儲能電能量應為多少，且是否可與其他併網型儲能聚合？","option_a":"1MWh，可聚合","option_b":"5MWh，不得聚合","option_c":"2MWh，可聚合","option_d":"2.5MWh，可任意聚合","answer":"B","explanation":"E-dReg電能量至少為參與容量2.5倍；2MW需至少5MWh，且應設定獨立報價代碼，不得與其他併網型儲能聚合。","source_title":"07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格","source_url":"","source_locator":"併網型儲能設備參與E-dReg","is_active":true,"tags":"單元07;易混淆;E-dReg;儲能;不得聚合"},
{"id":"C7-003","subject":"科目二｜電力交易平台市場規則","topic":"第7單元｜商品與資源","level":"3情境","question":"下列哪個敘述最符合教材對E-dReg的限制？","option_a":"E-dReg僅限併網型儲能設備參加","option_b":"E-dReg最適合只靠一般紙本需量反應","option_c":"E-dReg不需要任何儲能電量","option_d":"E-dReg可由任何資源任意聚合","answer":"A","explanation":"教材附件五註明E-dReg僅限併網型儲能設備參加。","source_title":"07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格","source_url":"","source_locator":"交易資源態樣與併網型儲能設備","is_active":true,"tags":"單元07;易混淆;E-dReg;資源態樣"},

{"id":"C8-001","subject":"科目二｜電力交易平台市場規則","topic":"第8單元｜市場時程","level":"3情境","question":"日前輔助服務市場每日報價與公布競價結果的時點容易混淆，下列何者正確？","option_a":"11時截止報價，16時公布競價結果","option_b":"16時截止報價，11時公布結果","option_c":"10時截止、12時公布","option_d":"全天皆無截止時間","answer":"A","explanation":"教材結語明列每日報價截止時點為11時，16時公布競價結果。","source_title":"08. 電力交易平台參考資料 日前輔助服務市場之運作","source_url":"","source_locator":"結語－市場每日時程","is_active":true,"tags":"單元08;易混淆;11時;16時"},
{"id":"C8-002","subject":"科目二｜電力交易平台市場規則","topic":"第8單元｜報價代碼","level":"3情境","question":"關於報價代碼，下列何者符合教材？","option_a":"可同時混合不同類型資源參與多項商品","option_b":"是投標、結清、結算及調度之依據，且僅得以同類型資源參與一項輔助服務商品","option_c":"只用於登入網站，與調度無關","option_d":"不需要交易容量","answer":"B","explanation":"教材指出報價代碼是投標、結清、結算與調度依據，並限制同類型資源參與一項商品。","source_title":"08. 電力交易平台參考資料 日前輔助服務市場之運作","source_url":"","source_locator":"結語－報價代碼原則","is_active":true,"tags":"單元08;易混淆;報價代碼"},
{"id":"C8-003","subject":"科目二｜電力交易平台市場規則","topic":"第8單元｜結算項目","level":"3情境","question":"哪一商品的結算價金依教材包含「容量費、效能費、服務品質指標、電能服務費」？","option_a":"dReg/sReg調頻備轉","option_b":"E-dReg","option_c":"補充備轉","option_d":"備用供電容量","answer":"B","explanation":"E-dReg結算包含容量費、效能費、服務品質指標與電能服務費；其他商品組成不同。","source_title":"08. 電力交易平台參考資料 日前輔助服務市場之運作","source_url":"","source_locator":"結語－各項交易商品結算","is_active":true,"tags":"單元08;易混淆;結算;E-dReg"},

{"id":"C9-001","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜買賣方資格","level":"3情境","question":"備用容量市場中，哪一方依教材明確「無須提供專業人員資格證明」？","option_a":"買方","option_b":"賣方","option_c":"雙方皆必須提供3張","option_d":"雙方皆不得提供","answer":"A","explanation":"教材在備用容量市場重要義務頁面明列買方無須提供專業人員資格證明。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"備用容量市場重要義務","is_active":true,"tags":"單元09;易混淆;買方;專業人員"},
{"id":"C9-002","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜交易容量","level":"3情境","question":"下列哪一組最能區分日前輔助服務市場小型資源聚合與備用容量市場交易容量規則？","option_a":"日前市場低於100kW可聚合同類型達100kW；備用容量市場基本交易單位10kW且交易資源不得聚合","option_b":"兩者都只能1MW以上且完全不能聚合","option_c":"日前市場10kW即可；備用市場至少100MW","option_d":"兩者皆無最低容量","answer":"A","explanation":"這是兩個市場非常容易混淆的門檻：日前市場有同類型資源聚合至100kW的規則；備用容量市場以10kW為基本交易單位且不得聚合。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"備用容量市場供給者參與方式；對照管理規範日前市場聚合規定","is_active":true,"tags":"單元09;易混淆;10kW;100kW;聚合"},
{"id":"C9-003","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜媒合時程","level":"3情境","question":"備用容量市場當次媒合起始日後，賣方設定標售資訊、資訊審查、買方競價的時段依序為何？","option_a":"第1-3日／第4-5日／第6-10日","option_b":"第1日／第2-8日／第9-10日","option_c":"第1-5日／第6日／第7日","option_d":"沒有固定順序","answer":"A","explanation":"教材時間表列示賣方第1至3日設定、4至5日審查、6至10日買方競價。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"交易媒合期間相關具體時間表","is_active":true,"tags":"單元09;易混淆;媒合時程"},
{"id":"C9-004","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜得標原則","level":"3情境","question":"同一賣方有50MW可售，三位買方出價不同。依教材，得標順序的第一判斷原則為何？","option_a":"出價最高者優先，再依序分配；同價時以完成出價時間決定優先","option_b":"出價最低者優先","option_c":"容量需求最大者永遠優先","option_d":"抽籤決定","answer":"A","explanation":"買方出價由高至低決定得標順序；同價時以完成出價時間決定。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"買方出價及得標原則","is_active":true,"tags":"單元09;易混淆;得標順序"},
{"id":"C9-005","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜重要義務","level":"3情境","question":"某容量已用來履行一位義務者的應備總供電容量，是否還可把同一容量再拿到備用容量交易專區出售？","option_a":"可以，只要價格不同","option_b":"不可以，同一單位容量不得重複交易","option_c":"可以，只要買方同意","option_d":"可以，但只能重複一次","answer":"B","explanation":"教材明列同一單位容量不得重複交易。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"備用容量市場重要義務","is_active":true,"tags":"單元09;易混淆;不得重複交易"},
{"id":"C9-006","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜超買限制","level":"3情境","question":"備用容量市場買方已透過雙邊契約籌措部分容量，下列何者正確？","option_a":"可完全忽略既有籌措量繼續無限超買","option_b":"應主動提報，且購買量不得高於應備總量扣除已籌措容量後的餘額","option_c":"雙邊契約不需揭露","option_d":"只有賣方才需要揭露雙邊契約","answer":"B","explanation":"教材規定買方不得超買，且既有雙邊契約或已籌措容量須主動提報。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"備用容量市場重要義務","is_active":true,"tags":"單元09;易混淆;超買;雙邊契約"},

{"id":"C10-001","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜再生能源挑戰","level":"3情境","question":"再生能源占比提高後，最直接增加調度難度的原因是什麼？","option_a":"間歇性與天候、日夜、季節因素使發電具有變動性","option_b":"再生能源全天輸出完全固定","option_c":"所有負載會自動消失","option_d":"電網不再需要供需平衡","answer":"A","explanation":"教材強調再生能源易受雲遮、日照、風力、天候、日夜與季節影響，增加供需平衡與調度風險。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"大量再生能源併網之衝擊","is_active":true,"tags":"單元10;易混淆;再生能源"},
{"id":"C10-002","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜SD-WAN","level":"3情境","question":"某題問平台如何提升與合格交易者之通訊品質與網路安全，並可自動調整通訊路徑。教材最直接對應哪一技術？","option_a":"SD-WAN","option_b":"紙本傳真","option_c":"燃料調度","option_d":"手動抄表","answer":"A","explanation":"SD-WAN具自動偵測通訊品質與調整通訊路徑的能力，教材用於平台與合格交易者訊息傳遞。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"運用數位科技整合全國電力資源","is_active":true,"tags":"單元10;易混淆;SD-WAN"},
{"id":"C10-003","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜PLEXOS","level":"3情境","question":"若題目描述「考量機組啟停、調節與輸電網潮流，以線性整數規劃求全系統資源配置最佳解」，最可能是哪一工具？","option_a":"PLEXOS","option_b":"AMI電表","option_c":"保護電驛","option_d":"SD-WAN","answer":"A","explanation":"教材說明PLEXOS以線性整數規劃執行最佳化排程，並可考量機組與網路物理限制。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"PLEXOS最佳化排程","is_active":true,"tags":"單元10;易混淆;PLEXOS"},
{"id":"C10-004","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜AFC儲能","level":"3情境","question":"儲能AFC在系統低頻與高頻時的典型動作，下列何者正確？","option_a":"低頻時快速放電、高頻時充電","option_b":"低頻時充電、高頻時放電","option_c":"不論頻率都只充電","option_d":"不論頻率都保持完全不動","answer":"A","explanation":"教材指出AFC利用儲能快速充放電特性，低頻時放電支援系統、高頻時充電吸收能量。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"平台推動成效－儲能AFC","is_active":true,"tags":"單元10;易混淆;AFC;儲能"},
{"id":"C10-005","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜分散式資源","level":"3情境","question":"商場暫停部分空調、資料中心短時間以UPS供電、工廠暫停部分製程，這些案例在教材中主要用來說明什麼？","option_a":"民間分散式資源可透過需量反應參與系統供需平衡","option_b":"所有用戶必須永久停電","option_c":"只有大型發電機組能參與平台","option_d":"分散式資源與電力交易平台無關","answer":"A","explanation":"教材以商場、冷凍廠、資料中心、工廠等案例說明需量反應與民間分散式資源參與。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"善用民間分散式資源","is_active":true,"tags":"單元10;易混淆;需量反應;分散式資源"},
{"id":"C10-006","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜未來技術","level":"2理解","question":"下列何者最不符合教材列出的電力交易平台未來技術精進方向？","option_a":"人工智慧與機器學習","option_b":"IoT、5G與SD-WAN","option_c":"最佳化演算法、大數據與平行運算","option_d":"全面回到人工紙本、不使用數位技術","answer":"D","explanation":"教材列出高速運算、AI、機器學習、IoT、5G、SD-WAN、最佳化演算法、大數據、平行運算、區塊鏈、數位簽章等方向。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"電力交易平台未來技術持續精進方向","is_active":true,"tags":"單元10;易混淆;未來技術"}
]);