window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat(
[
  {
    "id": "HV01-001",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜可傳輸能力",
    "level": "3情境計算",
    "cognitive": "公式應用",
    "question": "某區域間總傳輸能力（TTC）為4,400MW，預估尖峰電力潮流量為1,564MW。依教材，該區域可傳輸能力（ATC）為何？",
    "option_a": "2,836MW",
    "option_b": "5,964MW",
    "option_c": "1,564MW",
    "option_d": "4,400MW",
    "answer": "A",
    "explanation": "ATC＝TTC－預估尖峰電力潮流量＝4,400－1,564＝2,836MW。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－區域間總傳輸能力與可傳輸能力",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;TTC;ATC;計算"
  },
  {
    "id": "HV01-002",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜區域間總傳輸能力",
    "level": "3情境",
    "cognitive": "定義辨識",
    "question": "某人主張TTC只是『目前線路實際正在傳多少電』。依教材，哪個修正最正確？",
    "option_a": "TTC是檢討超高壓主幹線發生N-1或N-2事故後，仍不違反安全指標的最大傳輸能力",
    "option_b": "TTC就是當下實際潮流量",
    "option_c": "TTC等於ATC加上備轉容量",
    "option_d": "TTC只代表變電所裝置容量",
    "answer": "A",
    "explanation": "教材將TTC定義為檢討區域間超高壓主幹線在N-1或N-2事故跳脫後，不違反安全性指標的最大傳輸能力。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－TTC定義",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;TTC;N-1;N-2"
  },
  {
    "id": "HV01-003",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜電壓控制",
    "level": "3情境",
    "cognitive": "標準辨識",
    "question": "超高壓變電所161kV側匯流排量得166kV。若只依教材所列161kV±5%標準判斷，何者正確？",
    "option_a": "仍在±5%範圍內",
    "option_b": "一定超出標準，因只能±1.5%",
    "option_c": "一定超出標準，因只能±2.5%",
    "option_d": "教材沒有161kV電壓控制標準",
    "answer": "A",
    "explanation": "161kV±5%的範圍約為152.95～169.05kV，166kV仍在範圍內。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－台電系統電壓控制標準",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;161kV;±5%;電壓"
  },
  {
    "id": "HV01-004",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜電壓控制",
    "level": "2理解",
    "cognitive": "數字辨識",
    "question": "依教材，超高壓、一次變電所69kV匯流排電壓應維持在標準值的哪個範圍？",
    "option_a": "±1.5%",
    "option_b": "±5%",
    "option_c": "±2.5%",
    "option_d": "±10%",
    "answer": "A",
    "explanation": "教材列示69kV匯流排電壓維持在標準值±1.5%範圍內。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－台電系統電壓控制標準",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;69kV;±1.5%;電壓"
  },
  {
    "id": "HV01-005",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜電壓控制",
    "level": "3情境",
    "cognitive": "層級辨識",
    "question": "題目若描述22.8kV或11.4kV低壓側匯流排，依教材最應聯想到哪一電壓允許範圍？",
    "option_a": "標準值±2.5%",
    "option_b": "161kV±5%",
    "option_c": "標準值±1.5%",
    "option_d": "固定不得有任何偏差",
    "answer": "A",
    "explanation": "教材列示二次變電所等低壓側22.8kV、11.4kV匯流排維持在標準值±2.5%。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－台電系統電壓控制標準",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;22.8kV;11.4kV;±2.5%"
  },
  {
    "id": "HV01-006",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜無效電力",
    "level": "3情境",
    "cognitive": "原則判斷",
    "question": "若電壓調節與無效電力調度無法同時兼顧，依教材應如何處理？",
    "option_a": "優先電壓調節，且無效電力原則上避免長距離大量輸送",
    "option_b": "優先讓無效電力長距離輸送，不必顧電壓",
    "option_c": "兩者均可忽略",
    "option_d": "只看有功功率，不需考慮無效電力",
    "answer": "A",
    "explanation": "教材指出電壓調節與無效電力調整密切相關；無效電力應避免長距離大量輸送，若二者不能兼顧，以電壓調節優先。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－電壓調節與無效電力",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;無效電力;電壓優先"
  },
  {
    "id": "HV01-007",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜備用容量",
    "level": "3情境計算",
    "cognitive": "公式應用",
    "question": "某年度系統規劃淨尖峰能力45,000MW、系統尖峰負載40,000MW。依教材公式，備用容量率為何？",
    "option_a": "12.5%",
    "option_b": "11.1%",
    "option_c": "5%",
    "option_d": "112.5%",
    "answer": "A",
    "explanation": "備用容量率＝(45,000－40,000)÷40,000×100%＝12.5%。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "貳、台灣電力系統之電源結構－備用容量率公式",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;備用容量率;計算"
  },
  {
    "id": "HV01-008",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜備用與備轉",
    "level": "3情境",
    "cognitive": "條件比較",
    "question": "為何同一套『歲修、小修、故障等實際不可用因素』在備用容量與備轉容量概念中處理方式不同？",
    "option_a": "備用容量以正常發電下的規劃淨尖峰能力衡量年度充裕；備轉容量的運轉淨尖峰能力會反映當天歲修、故障等實際限制",
    "option_b": "兩者都完全不考慮任何機組狀況",
    "option_c": "只有備用容量會扣除故障機組，備轉容量不會",
    "option_d": "兩者只差名稱，計算基礎相同",
    "answer": "A",
    "explanation": "教材說明備用容量採系統規劃淨尖峰能力，偏年度規劃；備轉容量採當天系統運轉淨尖峰能力，會扣除歲修、小修、故障等可用性限制。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "貳、台灣電力系統之電源結構－備用容量與備轉容量",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;備用容量;備轉容量;運轉淨尖峰能力"
  },
  {
    "id": "HV01-009",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜可傳輸能力",
    "level": "3情境",
    "cognitive": "趨勢推論",
    "question": "若某區域TTC維持不變，但預估尖峰電力潮流量增加，依ATC公式，最合理的結果為何？",
    "option_a": "ATC下降",
    "option_b": "ATC上升",
    "option_c": "ATC一定不變",
    "option_d": "ATC變成負載率",
    "answer": "A",
    "explanation": "ATC＝TTC－預估尖峰電力潮流量；TTC不變而潮流量增加，ATC會下降。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－ATC公式",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;ATC;趨勢"
  },
  {
    "id": "HV01-010",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第1單元｜供電系統",
    "level": "2理解",
    "cognitive": "流程辨識",
    "question": "大型發電廠產生電力後，依教材所示台電供電系統，哪一流程最接近實際？",
    "option_a": "先升壓至345kV超高壓輸送，再經變電所降為161kV、69kV等層級",
    "option_b": "直接以11.4kV長距離輸送全台",
    "option_c": "先降成低壓再升為345kV",
    "option_d": "大型電廠不需變壓器即可直接供民生用戶",
    "answer": "A",
    "explanation": "教材說明大型發電廠先經變壓器升壓至345kV超高壓輸送，再經各級變電所降壓。",
    "source_title": "01. 電力交易平台參考資料 台灣電力系統概論",
    "source_url": "",
    "source_locator": "參、台灣電力系統之電網結構－台電供電系統",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元01;已核對;高鑑別;345kV;161kV;69kV;供電系統"
  },
  {
    "id": "HV02-001",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜機組調度",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "某機組適合24小時持續發電，教材舉例包括核能、燃煤。它最接近哪一類機組？",
    "option_a": "基載機組",
    "option_b": "中載機組",
    "option_c": "尖載機組",
    "option_d": "備轉機組",
    "answer": "A",
    "explanation": "教材定義基載機組為24小時持續不斷發電的機組，例示核能、燃煤。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－滿足負載的機組調度原則",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;基載;核能;燃煤"
  },
  {
    "id": "HV02-002",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜機組調度",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "複循環燃氣機組可在一天中啟停，並可提供電能與輔助服務。依教材較接近哪一類？",
    "option_a": "中載機組",
    "option_b": "基載機組",
    "option_c": "僅備轉機組",
    "option_d": "輸電設備",
    "answer": "A",
    "explanation": "教材以複循環燃氣作為中載機組例子，並列其可提供電能與輔助服務。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－滿足負載的機組調度原則",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;中載;複循環燃氣"
  },
  {
    "id": "HV02-003",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜機組調度",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "某機組一天可數次啟停、反應速度快，主要用於尖峰需求。依教材最可能是哪類機組？",
    "option_a": "尖載機組",
    "option_b": "基載機組",
    "option_c": "容量市場",
    "option_d": "配電變壓器",
    "answer": "A",
    "explanation": "尖載機組可一天數次啟停且反應快速，例示燃油、水力、燃氣。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－滿足負載的機組調度原則",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;尖載;快速反應"
  },
  {
    "id": "HV02-004",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜機組調度",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "若題目描述『需要待機準備應急，例示燃油、水力、燃氣，主要提供輔助服務』，應選何者？",
    "option_a": "備轉機組",
    "option_b": "基載機組",
    "option_c": "零售市場",
    "option_d": "變壓器",
    "answer": "A",
    "explanation": "教材將需待機準備應急的機組稱為備轉機組。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－滿足負載的機組調度原則",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;備轉機組;應急"
  },
  {
    "id": "HV02-005",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜短期負載預測",
    "level": "3情境",
    "cognitive": "資訊整合",
    "question": "值班人員要做短期負載預測。下列哪一組資料與流程最符合教材？",
    "option_a": "未來7日天氣、歷史負載與節日關聯輸入預測軟體，再由人員依最新狀況調整",
    "option_b": "只看去年同一天，不考慮天氣",
    "option_c": "只依人口長期趨勢，不需即時資料",
    "option_d": "完全由人工猜測，不使用預測軟體",
    "answer": "A",
    "explanation": "教材指出短期預測會使用未來7日天氣、歷史負載型態、特殊節日與氣象相關性等，再由人員依最新情況調整。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "貳、負載預測－短期負載預測方法",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;7日天氣;歷史負載;人工調整"
  },
  {
    "id": "HV02-006",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜負載預測",
    "level": "3情境",
    "cognitive": "時間尺度",
    "question": "『下一小時可調度量是否足夠』與『多年後電源開發』分別最接近負載預測的哪兩種用途？",
    "option_a": "短期／即時調度參考；長期電源開發規劃",
    "option_b": "兩者皆只屬年度財務預測",
    "option_c": "前者長期、後者短期",
    "option_d": "兩者都與負載預測無關",
    "answer": "A",
    "explanation": "教材將負載預測涵蓋從秒、分鐘、小時到多年：近時段支援調度，長期趨勢支援電源開發規劃。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "貳、負載預測－負載預測時間尺度",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;短期;長期;電源開發"
  },
  {
    "id": "HV02-007",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜負載特性",
    "level": "3情境",
    "cognitive": "因果判斷",
    "question": "夏季氣溫上升時，為何系統尖峰負載可能更敏感？",
    "option_a": "冷氣空調大量使用，使氣溫變化與系統負載關係更密切",
    "option_b": "因為氣溫越高所有工廠一定停工",
    "option_c": "因為輸電線會自動增加發電量",
    "option_d": "教材指出氣溫與負載完全無關",
    "answer": "A",
    "explanation": "教材指出冷氣空調大量使用，使夏季尖峰負載對氣溫變化愈來愈敏感。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "貳、負載預測－台灣電力系統負載特性",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;夏季;氣溫;空調"
  },
  {
    "id": "HV02-008",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜抽蓄水力",
    "level": "3情境",
    "cognitive": "多條件判斷",
    "question": "下列哪一描述最符合教材對抽蓄水力的系統貢獻？",
    "option_a": "低負載時可抽水填谷，負載突升時可快速解聯抽水並併聯發電，且可提供調頻與備轉",
    "option_b": "只能在離峰發電，不能抽水",
    "option_c": "併聯通常需數小時，無法支援快速需求",
    "option_d": "只具有灌溉功能，與電力調度無關",
    "answer": "A",
    "explanation": "教材指出抽蓄可在低負載抽水、負載突升時快速切換發電，併聯約3分鐘，並提供調頻、快速備轉、補充備轉等。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－抽蓄水力對系統之貢獻",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;抽蓄;3分鐘;填谷削峰;調頻"
  },
  {
    "id": "HV02-009",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜水力調度",
    "level": "3情境",
    "cognitive": "資源比較",
    "question": "一般水庫式或調整池式水力在尖峰時段的角色，依教材最合理的是？",
    "option_a": "可依水資源運用發電，尖峰時代替高成本機組並提供多種備轉服務",
    "option_b": "只能當基載24小時滿載",
    "option_c": "不可提供任何輔助服務",
    "option_d": "只能在市場關閉時運轉",
    "answer": "A",
    "explanation": "教材指出一般水庫式與調整池式水力可在尖峰時取代高成本機組，並提供快速備轉、調頻、即時及補充備轉。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－水力電廠調度原則",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;水庫式水力;尖峰;備轉"
  },
  {
    "id": "HV02-010",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第2單元｜電源配置限制",
    "level": "3情境",
    "cognitive": "限制辨識",
    "question": "規劃電源調度時，下列哪一項最不符合教材列示的限制或考量？",
    "option_a": "股票市場當日成交量",
    "option_b": "機組大修與故障",
    "option_c": "環評承諾與操作許可",
    "option_d": "下游用水需求與天然氣安全存量",
    "answer": "A",
    "explanation": "教材列出機組檢修故障、環評與許可、下游用水、電網安全、天然氣安全存量、法規與IPP合約等限制，未列股票成交量。",
    "source_title": "02. 電力交易平台參考資料 電力系統運轉與調度",
    "source_url": "",
    "source_locator": "參、電源調度－電源配置原則及限制",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元02;已核對;高鑑別;調度限制;環評;水資源;天然氣"
  },
  {
    "id": "HV03-001",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜市場架構",
    "level": "3情境",
    "cognitive": "目的辨識",
    "question": "若政策目標是『開放發電自由競爭、促進發電效率』，依教材最接近哪一類市場？",
    "option_a": "電能批發市場",
    "option_b": "容量市場",
    "option_c": "輔助服務市場",
    "option_d": "零售市場",
    "answer": "A",
    "explanation": "教材將電能批發市場目的列為開放發電自由競爭、促進發電效率。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "壹、國外電力市場概要－電力市場架構",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;批發電能市場;競爭;效率"
  },
  {
    "id": "HV03-002",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜市場架構",
    "level": "3情境",
    "cognitive": "目的辨識",
    "question": "若目標是降低價格波動並鼓勵發電端投資，依教材最接近哪一市場？",
    "option_a": "容量市場",
    "option_b": "零售市場",
    "option_c": "日前輔助服務市場",
    "option_d": "只做即時結算的市場",
    "answer": "A",
    "explanation": "教材指出容量市場可降低市場價格波動性並鼓勵發電端投資。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "壹、國外電力市場概要－容量市場",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;容量市場;投資;價格波動"
  },
  {
    "id": "HV03-003",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜市場架構",
    "level": "3情境",
    "cognitive": "目的辨識",
    "question": "『在電能即時調度前，確保電能、電壓、頻率之平衡及穩定』描述的是哪一市場？",
    "option_a": "輔助服務市場",
    "option_b": "零售市場",
    "option_c": "容量市場",
    "option_d": "外匯市場",
    "answer": "A",
    "explanation": "教材將此目的列於輔助服務市場。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "壹、國外電力市場概要－輔助服務市場",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;輔助服務市場;電壓;頻率"
  },
  {
    "id": "HV03-004",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜市場架構",
    "level": "2理解",
    "cognitive": "目的辨識",
    "question": "依教材，哪一市場的核心目的為開放用戶自由選擇電力來源？",
    "option_a": "零售市場",
    "option_b": "容量市場",
    "option_c": "輔助服務市場",
    "option_d": "備轉容量市場",
    "answer": "A",
    "explanation": "教材將零售市場目的列為開放用戶自由選擇電力來源。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "壹、國外電力市場概要－零售市場",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;零售市場;用戶選擇"
  },
  {
    "id": "HV03-005",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜市場結清",
    "level": "3情境",
    "cognitive": "價格形成",
    "question": "某市場的供給標單曲線與需求標單曲線相交。依教材概念，交點最接近代表什麼？",
    "option_a": "市場結清價格",
    "option_b": "固定政府補貼額",
    "option_c": "備用容量率",
    "option_d": "機組裝置容量",
    "answer": "A",
    "explanation": "教材以一般商品市場概念說明，供需曲線交集點即為市場結清價格。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "電力市場概念－供需曲線與市場結清價格",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;市場結清價格;供需曲線"
  },
  {
    "id": "HV03-006",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜共同最佳化",
    "level": "3情境",
    "cognitive": "多條件判斷",
    "question": "共同最佳化若只挑『報價最低的一台機組』而完全不考慮升降載、最小運轉時間與輔助服務需求，為何不符合教材？",
    "option_a": "共同最佳化目標是在多項機組與系統限制下最小化全系統發電成本",
    "option_b": "共同最佳化只看機組名稱",
    "option_c": "共同最佳化不需要任何限制條件",
    "option_d": "共同最佳化的目標是最大化停電時間",
    "answer": "A",
    "explanation": "教材的共同最佳化以Min全系統發電成本為目標，並納入最大/小出力、升降載率、最小運轉/停機時間、輔助服務能力、系統負載與需求量等限制。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "電力市場－共同最佳化",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;共同最佳化;系統成本;限制條件"
  },
  {
    "id": "HV03-007",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜電力交易商品",
    "level": "3情境",
    "cognitive": "分類",
    "question": "某商品主要目的為吸引發電投資並確保容量充裕性。依教材應歸在哪一類交易？",
    "option_a": "容量交易",
    "option_b": "電能交易",
    "option_c": "零售用戶選擇",
    "option_d": "頻率量測",
    "answer": "A",
    "explanation": "教材將容量交易目的列為吸引發電投資、確保容量充裕性。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "電力市場交易商品－容量交易、電能、輔助服務",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;容量交易;容量充裕"
  },
  {
    "id": "HV03-008",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜未來市場架構",
    "level": "3情境",
    "cognitive": "時間尺度",
    "question": "下列哪一配對最符合教材對未來市場架構的說明？",
    "option_a": "容量市場－遠期；日前市場－調度日前；小時前－依機組狀況再調整；即時市場－調度日即時交易",
    "option_b": "容量市場－5分鐘；日前市場－遠期十年；即時市場－隔年",
    "option_c": "四種市場時間尺度完全相同",
    "option_d": "即時市場只處理遠期容量",
    "answer": "A",
    "explanation": "教材依時間尺度區分容量、日前、小時前調整及即時市場。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "參、國內電力市場規劃－未來架構",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;容量市場;日前;小時前;即時"
  },
  {
    "id": "HV03-009",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜LMP",
    "level": "3情境",
    "cognitive": "概念辨識",
    "question": "在LMP概念下，某電氣節點『再增加下一個1MW』所需增加的成本，最接近何者？",
    "option_a": "該節點的邊際成本概念",
    "option_b": "所有機組平均建置成本",
    "option_c": "用戶基本電費",
    "option_d": "容量市場年費",
    "answer": "A",
    "explanation": "教材以機組報價為基礎，將LMP說明為在一電氣節點增加下一個MW所需增加的邊際成本。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "貳、國外電力市場運作說明－日前市場價格及結果公告",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;LMP;邊際成本"
  },
  {
    "id": "HV03-010",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第3單元｜LMP結算點",
    "level": "3情境",
    "cognitive": "比較",
    "question": "關於LMP結算點，下列哪一敘述符合教材？",
    "option_a": "負載區域取區域內負載點LMP的加權平均；Hub則依設定之匯流排LMP取平均",
    "option_b": "負載區域與Hub都一定取全國最高LMP",
    "option_c": "資源節點一定取所有節點平均",
    "option_d": "LMP與電氣節點無關",
    "answer": "A",
    "explanation": "教材區分Resource Node、Load Zone與Hub：Load Zone為負載點LMP加權平均，Hub為指定匯流排LMP平均。",
    "source_title": "03. 電力交易平台參考資料 電力交易市場概述",
    "source_url": "",
    "source_locator": "貳、國外電力市場運作說明－LMP結算點",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元03;已核對;高鑑別;LMP;Load Zone;Hub"
  },
  {
    "id": "HV04-001",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜系統可靠度",
    "level": "3情境",
    "cognitive": "概念比較",
    "question": "某規劃問題問『未來5～10年是否有足夠容量』；另一運轉問題問『如何讓供需每分每秒保持動態平衡』。依教材兩者分別偏向哪個概念？",
    "option_a": "系統容量充裕性／系統品質與安全",
    "option_b": "系統品質與安全／系統容量充裕性",
    "option_c": "兩者都只屬零售市場",
    "option_d": "兩者都只看線路損失",
    "answer": "A",
    "explanation": "教材將系統可靠度分為容量充裕性與品質安全；長期備用容量偏充裕性，動態平衡與輔助服務偏安全。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "壹、輔助服務之目的－System Reliability",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;adequacy;security;可靠度"
  },
  {
    "id": "HV04-002",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜系統可靠度",
    "level": "2理解",
    "cognitive": "時間尺度",
    "question": "教材將備用容量率與備轉容量率的時間尺度如何區分？",
    "option_a": "備用容量率偏5～10年；備轉容量率偏2日內",
    "option_b": "兩者皆只看5分鐘",
    "option_c": "備用容量率2日內；備轉容量率5～10年",
    "option_d": "兩者皆固定為一年",
    "answer": "A",
    "explanation": "教材將長期容量充裕以備用容量率（5～10年）說明，短期則以備轉容量率（2日內）說明。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "壹、輔助服務之目的－系統容量充裕性",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;5-10年;2日內;備用;備轉"
  },
  {
    "id": "HV04-003",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜輔助服務定義",
    "level": "3情境",
    "cognitive": "定義辨識",
    "question": "下列哪一描述最完整符合教材對『輔助服務』的定義？",
    "option_a": "維持系統安全穩定，事故後協助恢復正常，並滿足電壓與頻率要求的一系列服務",
    "option_b": "只負責收取電費",
    "option_c": "只用於增加發電廠裝置容量",
    "option_d": "只處理燃料採購",
    "answer": "A",
    "explanation": "教材將輔助服務定義為維持系統安全穩定、事故後恢復正常並滿足電壓與頻率要求的一系列服務。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "壹、輔助服務之目的－輔助服務定義",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;輔助服務;電壓;頻率"
  },
  {
    "id": "HV04-004",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜全黑啟動",
    "level": "3情境",
    "cognitive": "服務辨識",
    "question": "系統全停電後，需要發電機組自行起動並向外加壓送電，使系統逐步恢復。這是哪一項輔助服務？",
    "option_a": "全黑啟動",
    "option_b": "E-dReg",
    "option_c": "補充備轉",
    "option_d": "容量交易",
    "answer": "A",
    "explanation": "教材將全黑啟動定義為系統全停電時，發電機組自行起動並向外加壓送電以恢復系統。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－我國輔助服務項目分類",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;全黑啟動;Black Start"
  },
  {
    "id": "HV04-005",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜無效電力及電壓調整",
    "level": "3情境",
    "cognitive": "服務辨識",
    "question": "若系統的需求是『把電壓維持在目標範圍』，最直接對應哪一項服務？",
    "option_a": "無效電力及電壓調整",
    "option_b": "全黑啟動",
    "option_c": "容量市場",
    "option_d": "零售市場",
    "answer": "A",
    "explanation": "教材將無效電力及電壓調整說明為使系統電壓維持在目標範圍內的電壓調整服務。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－我國輔助服務項目分類",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;無效電力;電壓調整"
  },
  {
    "id": "HV04-006",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜再生能源衝擊",
    "level": "3情境",
    "cognitive": "因果判斷",
    "question": "大量再生能源併網、傳統機組減少時，教材指出哪一風險可能增加？",
    "option_a": "輔助服務取得較困難",
    "option_b": "所有輔助服務需求自動歸零",
    "option_c": "系統慣量一定增加",
    "option_d": "電壓與頻率不再需要控制",
    "answer": "A",
    "explanation": "教材列示傳統機組減少會使輔助服務取得困難。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－大量再生能源併網之衝擊",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;再生能源;傳統機組;輔助服務"
  },
  {
    "id": "HV04-007",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜系統慣量",
    "level": "3情境",
    "cognitive": "因果判斷",
    "question": "系統慣量不足時，依教材最直接的影響為何？",
    "option_a": "頻率響應變差",
    "option_b": "容量市場自動取消",
    "option_c": "電壓一定固定不變",
    "option_d": "負載預測完全不需要",
    "answer": "A",
    "explanation": "教材明列系統慣量不足會使頻率響應變差。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－大量再生能源併網之衝擊",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;慣量;頻率響應"
  },
  {
    "id": "HV04-008",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜無效電力",
    "level": "3情境",
    "cognitive": "因果判斷",
    "question": "主動式無效電力來源不足時，教材指出最可能造成哪一問題？",
    "option_a": "系統電壓不穩定",
    "option_b": "容量市場價格一定下降",
    "option_c": "電能需求歸零",
    "option_d": "市場不再需要報價",
    "answer": "A",
    "explanation": "教材列示主動式無效電力來源不足會導致系統電壓不穩定。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－大量再生能源併網之衝擊",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;無效電力;電壓不穩"
  },
  {
    "id": "HV04-009",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜淨負載變化",
    "level": "3情境",
    "cognitive": "風險辨識",
    "question": "下午時段負載快速上升時，教材指出可能增加哪一系統風險？",
    "option_a": "低頻電驛動作卸載",
    "option_b": "高頻一定持續上升且不需控制",
    "option_c": "所有機組自動停機",
    "option_d": "只影響零售電價，與系統安全無關",
    "answer": "A",
    "explanation": "教材指出下午時段負載上升速度快，易導致低頻電驛動作卸載。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－大量再生能源併網之衝擊",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;下午爬坡;低頻;卸載"
  },
  {
    "id": "HV04-010",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第4單元｜商品功能",
    "level": "3情境",
    "cognitive": "多情境辨識",
    "question": "下列哪一配對最符合教材對我國輔助服務商品功能的說明？",
    "option_a": "E-dReg－頻率調整兼尖離峰電能移轉；即時備轉－應付機組跳機等緊急事件；補充備轉－應付負載突增或預測誤差",
    "option_b": "E-dReg－只做年度容量規劃；即時備轉－零售電價；補充備轉－股票交易",
    "option_c": "三者皆只做全黑啟動",
    "option_d": "即時與補充備轉都只用於長期5～10年容量規劃",
    "answer": "A",
    "explanation": "教材分別說明E-dReg兼具頻率調整與電能移轉，即時備轉因應機組跳機等緊急事件，補充備轉因應負載突增與供需預測誤差等。",
    "source_title": "04. 電力交易平台參考資料 輔助服務概論",
    "source_url": "",
    "source_locator": "參、國內輔助服務介紹－我國輔助服務項目分類",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元04;已核對;高鑑別;E-dReg;即時備轉;補充備轉"
  },
  {
    "id": "HV10-001",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜能源轉型",
    "level": "3情境",
    "cognitive": "趨勢辨識",
    "question": "依教材，隨再生能源發電量增加與間歇性提高，電網供需平衡模式正朝哪個方向調整？",
    "option_a": "由大型火力集中供應逐漸轉為多元化電力資源共同維護供需平衡",
    "option_b": "由多元資源完全退回單一電廠供應",
    "option_c": "不再需要任何調度",
    "option_d": "只靠零售電價維持頻率",
    "answer": "A",
    "explanation": "教材指出淨零趨勢下，再生能源間歇性提高調度風險，電網逐漸由集中供應轉向多元化電力資源共同維護供需平衡。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "壹、能源轉型下電力挑戰與因應－因應再生能源併網",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;能源轉型;多元資源;間歇性"
  },
  {
    "id": "HV10-002",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜虛擬電廠",
    "level": "3情境",
    "cognitive": "角色理解",
    "question": "教材所稱電力交易平台扮演『虛擬電廠調度的重要角色』，核心作法最接近何者？",
    "option_a": "整合大量分散式能源，提供輔助服務並協助穩定電網頻率",
    "option_b": "把所有分散式資源永久關閉",
    "option_c": "只提供紙本帳單",
    "option_d": "只管理大型燃煤電廠的人事",
    "answer": "A",
    "explanation": "教材指出平台整合大量分散式能源，提供系統輔助服務並穩定電網頻率。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "貳、電力交易平台創新技術應用－運用數位科技整合全國電力資源",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;虛擬電廠;分散式能源"
  },
  {
    "id": "HV10-003",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜SD-WAN",
    "level": "3情境",
    "cognitive": "功能辨識",
    "question": "某通訊方案可自動偵測通訊品質、調整通訊路徑，並強調不同業者資訊不可互相流通。依教材最接近哪項技術？",
    "option_a": "SD-WAN",
    "option_b": "單純紙本郵寄",
    "option_c": "一般類比電表",
    "option_d": "燃氣輪機控制器",
    "answer": "A",
    "explanation": "教材說明SD-WAN具自動偵測通訊品質與自動調整路徑功能，並有助提升資訊隔離與網路安全。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "貳、電力交易平台創新技術應用－SD-WAN",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;SD-WAN;通訊品質;網路安全"
  },
  {
    "id": "HV10-004",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜短期負載預測模型",
    "level": "3情境",
    "cognitive": "模型理解",
    "question": "平台短期負載預測模組若同時使用歷史用電趨勢、天氣、節慶假日，並結合殘差類神經網路與多重方程時間序列模型，最符合教材哪一描述？",
    "option_a": "利用多模型與多來源資料提升即時全系統用電需求預測",
    "option_b": "只用單一固定常數預測",
    "option_c": "完全不使用天氣資料",
    "option_d": "只用年度人口統計，不做短期預測",
    "answer": "A",
    "explanation": "教材說明短期負載預測模組結合殘差類神經網路、多重方程時間序列模型，以及天氣、節慶等因素。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "貳、電力交易平台創新技術應用－短期負載預測模型",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;負載預測;神經網路;時間序列"
  },
  {
    "id": "HV10-005",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜Ensemble Learning",
    "level": "3情境",
    "cognitive": "方法辨識",
    "question": "短期負載預測中採用Ensemble Learning的主要目的為何？",
    "option_a": "進行模型融合以提高預測精度",
    "option_b": "讓每個模型互相取消所有結果",
    "option_c": "只為了增加資料檔案大小",
    "option_d": "取代所有氣象與歷史資料",
    "answer": "A",
    "explanation": "教材明列採用Ensemble Learning進行模型融合，以提高預測精度。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "貳、電力交易平台創新技術應用－短期負載預測模型",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;Ensemble Learning;模型融合"
  },
  {
    "id": "HV10-006",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜PLEXOS",
    "level": "3情境",
    "cognitive": "最佳化理解",
    "question": "依教材，PLEXOS在電力交易中心的主要用途為何？",
    "option_a": "運用線性整數規劃執行最佳化排程，求得全系統電力資源配置最佳解",
    "option_b": "只做文書排版",
    "option_c": "只預測股票價格",
    "option_d": "只管理用戶姓名資料",
    "answer": "A",
    "explanation": "教材指出PLEXOS運用線性整數規劃執行最佳化排程，求得全系統電力資源配置最佳解。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "貳、電力交易平台創新技術應用－PLEXOS最佳化排程",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;PLEXOS;線性整數規劃;最佳化"
  },
  {
    "id": "HV10-007",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜PLEXOS",
    "level": "3情境",
    "cognitive": "限制辨識",
    "question": "下列哪一組是教材明列PLEXOS可考慮的電力系統物理特性？",
    "option_a": "發電機組啟動、停機、調節，以及輸電網絡結構潮流",
    "option_b": "公司員工生日與停車位",
    "option_c": "股票市場成交量與匯率",
    "option_d": "用戶社群媒體按讚數",
    "answer": "A",
    "explanation": "教材指出PLEXOS可考慮機組啟動、停機、調節及輸電網絡結構潮流等物理特性。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "貳、電力交易平台創新技術應用－PLEXOS最佳化排程",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;PLEXOS;機組限制;潮流"
  },
  {
    "id": "HV10-008",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜AFC儲能",
    "level": "3情境",
    "cognitive": "方向判斷",
    "question": "系統頻率偏低時，依教材AFC儲能的典型反應方向為何？",
    "option_a": "快速放電；高頻時則充電",
    "option_b": "低頻時充電、高頻時放電",
    "option_c": "無論高低頻都完全不動",
    "option_d": "低頻時只關閉通訊",
    "answer": "A",
    "explanation": "教材指出AFC儲能持續偵測頻率，發生擾動時可低頻快速放電、高頻充電。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "參、平台推動成效－提升電力系統韌性",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;AFC;低頻放電;高頻充電"
  },
  {
    "id": "HV10-009",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜需量反應",
    "level": "3情境",
    "cognitive": "案例辨識",
    "question": "教材以電信機房或資料中心為例，短時間降低用電時可由哪一設備供電？",
    "option_a": "UPS",
    "option_b": "汽車發電機固定供全廠",
    "option_c": "一般照明開關",
    "option_d": "只靠紙本通知",
    "answer": "A",
    "explanation": "教材案例指出電信機房與資料中心可降低用電，短時間由UPS供電。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "參、平台推動成效－分散式資源參與案例",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;需量反應;UPS;資料中心"
  },
  {
    "id": "HV10-010",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "第10單元｜未來發展願景",
    "level": "3情境",
    "cognitive": "綜合辨識",
    "question": "下列哪一項最不屬於教材所列電力交易平台未來發展願景？",
    "option_a": "增加對單一能源來源的依賴",
    "option_b": "增進供電穩定",
    "option_c": "降低運轉成本與國內碳排",
    "option_d": "刺激電力投資並開拓資源多樣性",
    "answer": "A",
    "explanation": "教材列出增進供電穩定、刺激投資、降低運轉成本與碳排、開拓資源多樣性等願景，並非增加單一能源依賴。",
    "source_title": "10.我國電力交易市場推動之方向與展望",
    "source_url": "",
    "source_locator": "肆、未來展望－電力交易平台未來發展願景",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元10;已核對;高鑑別;供電穩定;投資;碳排;資源多樣"
  }
]
);
