window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"H10-001","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜再生能源挑戰","level":"1基礎","question":"教材列示2023年台電系統發電量中，再生能源占比約為多少？","option_a":"5.8%","option_b":"6.3%","option_c":"8.6%","option_d":"9.9%","answer":"D","explanation":"教材列示再生能源占比由2020年5.8%、2021年6.3%、2022年8.6%增加至2023年9.9%。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"大量再生能源併網之衝擊","is_active":true,"tags":"單元10;再生能源"},
{"id":"H10-002","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜能源轉型","level":"2理解","question":"再生能源占比提高後，為何會增加系統調度難度？","option_a":"因其間歇性與天候、日夜、季節等因素影響","option_b":"因所有再生能源都固定全天滿載","option_c":"因不再需要任何電網","option_d":"因負載會完全消失","answer":"A","explanation":"教材指出再生能源受雲遮、日照、風力、天候、日夜及季節等影響，間歇性會提高供電穩定與調度風險。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"能源轉型下電力挑戰與因應","is_active":true,"tags":"單元10;能源轉型;間歇性"},
{"id":"H10-003","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜平台目標","level":"2理解","question":"電力交易平台設立的重要目標之一是什麼？","option_a":"吸引民間可調度的彈性電力資源加入","option_b":"排除所有分散式資源","option_c":"只讓大型燃煤機組參加","option_d":"取消所有輔助服務","answer":"A","explanation":"教材指出平台透過經濟共享的交易模式，吸引民間彈性電力資源加入，與大型機組共同維護能源安全。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"電力交易平台設立背景與目標","is_active":true,"tags":"單元10;平台目標"},
{"id":"H10-004","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜SD-WAN","level":"2理解","question":"教材中，SD-WAN技術在電力交易平台的重要功能為何？","option_a":"傳遞平台與合格交易者訊息，並可自動偵測通訊品質及調整路徑","option_b":"只用來列印紙本帳單","option_c":"只用來計算燃料成本","option_d":"取代所有交易表計","answer":"A","explanation":"教材說明SD-WAN可協助平台與合格交易者傳遞訊息，具自動偵測通訊品質及調整通訊路徑能力。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"運用數位科技整合全國電力資源","is_active":true,"tags":"單元10;SD-WAN;資通訊"},
{"id":"H10-005","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜PLEXOS","level":"2理解","question":"教材中的PLEXOS程式主要用於哪一項工作？","option_a":"執行最佳化排程，求得全系統電力資源配置最佳解","option_b":"製作電費帳單封面","option_c":"只統計員工人數","option_d":"只管理網站登入密碼","answer":"A","explanation":"教材指出PLEXOS運用線性整數規劃執行最佳化排程，並考量機組與輸電網路等物理特性。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"PLEXOS最佳化排程","is_active":true,"tags":"單元10;PLEXOS;最佳化"},
{"id":"H10-006","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜AFC儲能","level":"1基礎","question":"教材提到台電於2020年辦理的儲能自動頻率控制（AFC）調頻服務標案容量為多少？","option_a":"5MW","option_b":"10MW","option_c":"15MW","option_d":"50MW","answer":"C","explanation":"教材指出2020年辦理15MW儲能AFC調頻服務標案，為亞洲首例儲能AFC成功案例。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"平台推動成效－提升電力系統韌性","is_active":true,"tags":"單元10;AFC;儲能"},
{"id":"H10-007","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜分散式資源","level":"2理解","question":"下列何者符合教材所述「善用民間分散式資源」的概念？","option_a":"商場、工廠、資料中心可透過需量反應降低用電，儲能可追隨頻率充放電","option_b":"只有大型核能機組可以參與","option_c":"所有民間資源均不得進入平台","option_d":"需量反應只能增加負載","answer":"A","explanation":"教材舉例商場、冷凍廠、資料中心、自用發電及併網型儲能等多元資源參與平台。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"平台推動成效－善用民間分散式資源","is_active":true,"tags":"單元10;分散式資源;需量反應"},
{"id":"H10-008","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜未來技術","level":"2理解","question":"下列何者不是教材列出的電力交易平台未來技術持續精進方向？","option_a":"人工智慧與機器學習","option_b":"IoT、5G與SD-WAN","option_c":"區塊鏈與數位簽章","option_d":"完全改回人工紙本傳真作業","answer":"D","explanation":"教材列舉高速運算、AI、機器學習、IoT、5G、SD-WAN、最佳化演算法、大數據、平行運算、區塊鏈及數位簽章等技術。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"電力交易平台未來技術持續精進方向","is_active":true,"tags":"單元10;未來技術"}
]);