window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"H1-001","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電力系統架構","level":"1基礎","question":"依教材，電力系統主要由哪四個部分組成？","option_a":"發電、輸電、配電、售電","option_b":"發電、儲電、調度、售電","option_c":"輸電、變電、儲能、售電","option_d":"發電、燃料、配電、計費","answer":"A","explanation":"教材將電力系統分為發電、輸電、配電與售電四部分。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"壹、電力系統架構","is_active":true,"tags":"單元01;電力系統架構"},
{"id":"H1-002","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜備用與備轉","level":"2理解","question":"下列何者最能正確區分備用容量率與備轉容量率？","option_a":"備用看每日、備轉看每年","option_b":"備用看遠期供電充裕度、備轉看短期實際可調度裕度","option_c":"兩者完全相同","option_d":"備用只看電網、備轉只看售電","answer":"B","explanation":"備用容量率衡量遠期發電端供電可靠度；備轉容量率衡量短期實際可調度的發電容量裕度。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"台灣電力系統之備用與備轉容量","is_active":true,"tags":"單元01;備用容量;備轉容量"},
{"id":"H1-003","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜備用容量計算","level":"3情境計算","question":"某年度系統規劃淨尖峰能力為45,000MW，系統尖峰負載為40,000MW。依教材公式，備用容量率為多少？","option_a":"10%","option_b":"11.1%","option_c":"12.5%","option_d":"15%","answer":"C","explanation":"(45,000－40,000)÷40,000×100%=12.5%。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"備用容量率公式","is_active":true,"tags":"單元01;計算;備用容量率"},
{"id":"H1-004","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜備轉容量計算","level":"3情境計算","question":"某日系統運轉淨尖峰能力為38,500MW，系統瞬時尖峰負載為35,000MW。依教材公式，備轉容量率為多少？","option_a":"7.5%","option_b":"10%","option_c":"12.5%","option_d":"15%","answer":"B","explanation":"(38,500－35,000)÷35,000×100%=10%。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"備轉容量率公式","is_active":true,"tags":"單元01;計算;備轉容量率"},
{"id":"H1-005","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電網結構","level":"1基礎","question":"下列何者不是教材列舉的電網結構主要設備？","option_a":"輸電線路","option_b":"變壓器","option_c":"保護電驛","option_d":"燃料儲槽","answer":"D","explanation":"教材列舉輸電線路、變壓器、電容器、電抗器、保護電驛等電網設備。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"電網結構","is_active":true,"tags":"單元01;電網結構"},
{"id":"H1-006","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電壓控制","level":"1基礎","question":"教材中，超高壓變電所161kV側匯流排電壓應維持在標準值多少範圍內？","option_a":"±1%","option_b":"±1.5%","option_c":"±2.5%","option_d":"±5%","answer":"D","explanation":"161kV側匯流排電壓控制標準為161kV ±5%。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"台電系統電壓控制標準","is_active":true,"tags":"單元01;電壓控制"},
{"id":"H1-007","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電壓控制","level":"1基礎","question":"教材中，69kV匯流排電壓應維持在標準值多少範圍內？","option_a":"±1.5%","option_b":"±2.5%","option_c":"±5%","option_d":"±10%","answer":"A","explanation":"超高壓、一次變電所69kV匯流排電壓維持在標準值±1.5%。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"台電系統電壓控制標準","is_active":true,"tags":"單元01;電壓控制"},
{"id":"H1-008","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜負載限制","level":"2情境","question":"系統突發事故導致電源不足，必須立即且無預警採取限電措施，較符合哪一項？","option_a":"計畫性負載限制","option_b":"緊急負載限制","option_c":"年度負載預測","option_d":"日前市場結清","answer":"B","explanation":"緊急負載限制用於突發事故，屬立即實施且通常無法事先通知用戶的措施。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"系統安全監視控制、緊急應變－負載限制","is_active":true,"tags":"單元01;負載限制"}
]);