window.LOCAL_QUESTIONS = [
  {
    "id": "S1-001",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "輔助服務基礎",
    "level": "1基礎",
    "question": "依台電參考資料，電力系統為維持固定頻率，發電端需隨何者的變化進行相對應調整？",
    "option_a": "負載",
    "option_b": "輸電線長度",
    "option_c": "電表數量",
    "option_d": "電廠員工人數",
    "answer": "A",
    "explanation": "電力負載會持續變化，發電端必須配合負載調整，才能維持系統頻率穩定。",
    "source_title": "04. 電力交易平台參考資料－輔助服務概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "輔助服務目的與功能",
    "is_active": true,
    "tags": "60Hz;負載;輔助服務"
  },
  {
    "id": "S1-002",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "輔助服務基礎",
    "level": "1基礎",
    "question": "台灣電力系統正常運轉的頻率基準值為何？",
    "option_a": "50 Hz",
    "option_b": "55 Hz",
    "option_c": "60 Hz",
    "option_d": "65 Hz",
    "answer": "C",
    "explanation": "台灣電力系統以 60 Hz 為頻率基準值。",
    "source_title": "04. 電力交易平台參考資料－輔助服務概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "維持頻率固定 60Hz",
    "is_active": true,
    "tags": "60Hz;頻率"
  },
  {
    "id": "S1-003",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "容量概念",
    "level": "1基礎",
    "question": "依台電輔助服務參考資料，下列哪一項較屬於長期（約 5～10 年）供電規劃概念？",
    "option_a": "備用容量率",
    "option_b": "備轉容量率",
    "option_c": "即時備轉執行率",
    "option_d": "每秒執行率",
    "answer": "A",
    "explanation": "台電教材將「備用容量率」放在長期約 5～10 年的供電規劃。",
    "source_title": "04. 電力交易平台參考資料－輔助服務概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "長期/短期容量概念",
    "is_active": true,
    "tags": "備用容量;備轉容量"
  },
  {
    "id": "S1-004",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "容量概念",
    "level": "1基礎",
    "question": "依台電輔助服務參考資料，下列哪一項較屬於短期（約 2 日內）系統運轉概念？",
    "option_a": "備用容量率",
    "option_b": "備轉容量率",
    "option_c": "年發電量成長率",
    "option_d": "裝置容量成長率",
    "answer": "B",
    "explanation": "台電教材以「備轉容量率」描述短期約 2 日內的運轉需求。",
    "source_title": "04. 電力交易平台參考資料－輔助服務概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "長期/短期容量概念",
    "is_active": true,
    "tags": "備轉容量;短期調度"
  },
  {
    "id": "S1-005",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "輔助服務基礎",
    "level": "2理解",
    "question": "下列何者最能說明輔助服務在電力系統中的主要角色？",
    "option_a": "取代所有發電設備",
    "option_b": "提高電力系統穩定與可靠性",
    "option_c": "只用來計算電費",
    "option_d": "只提供再生能源憑證",
    "answer": "B",
    "explanation": "電能用來滿足負載需求；輔助服務則提高系統穩定與可靠性。",
    "source_title": "04. 電力交易平台參考資料－輔助服務概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "輔助服務功能",
    "is_active": true,
    "tags": "輔助服務;可靠度"
  },
  {
    "id": "S1-006",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "系統安全",
    "level": "2理解",
    "question": "下列何者符合台電教材所述的電網安全要求？",
    "option_a": "輸電線可長時間超載，只要頻率正常即可",
    "option_b": "僅需監視發電機，不需監視電壓",
    "option_c": "輸電網不超載，且電壓、相位與頻率在擾動後具有回復能力",
    "option_d": "只要尖峰負載降低即可視為安全",
    "answer": "C",
    "explanation": "電網安全包含避免輸電網超載，並維持電壓、相位與頻率在擾動後具有回復能力。",
    "source_title": "01. 電力交易平台參考資料－台灣電力系統概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "電網安全監視控制",
    "is_active": true,
    "tags": "電網安全;電壓;頻率"
  },
  {
    "id": "S1-007",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "負載限制",
    "level": "2理解",
    "question": "系統突發事故造成電源不足、設備超載或電壓嚴重偏低時，需立即採取且通常無法事前通知用戶的措施稱為何者？",
    "option_a": "計畫性負載限制",
    "option_b": "緊急負載限制",
    "option_c": "年度檢修",
    "option_d": "日前市場結清",
    "answer": "B",
    "explanation": "緊急負載限制因事故突然發生，屬立即因應措施，通常無法事前通知用戶。",
    "source_title": "01. 電力交易平台參考資料－台灣電力系統概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "負載限制",
    "is_active": true,
    "tags": "緊急負載限制"
  },
  {
    "id": "S1-008",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "負載限制",
    "level": "2理解",
    "question": "若已預測隔日可能電源不足，並先執行用戶臨時減少用電等措施後仍不足，較可能採取哪一種措施？",
    "option_a": "計畫性負載限制",
    "option_b": "緊急跳機",
    "option_c": "調頻備轉測試",
    "option_d": "市場註冊",
    "answer": "A",
    "explanation": "計畫性負載限制用於預測隔日電源供應不足，且其他措施仍不足的情況。",
    "source_title": "01. 電力交易平台參考資料－台灣電力系統概論",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "負載限制",
    "is_active": true,
    "tags": "計畫性負載限制"
  },
  {
    "id": "S1-009",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "水力調度",
    "level": "2理解",
    "question": "抽蓄水力機組在電力系統中的典型功能，下列何者最適當？",
    "option_a": "只在離峰時發電",
    "option_b": "可利用離峰抽水、尖峰發電，並支援調頻與備轉",
    "option_c": "只能提供太陽光電預測",
    "option_d": "不能參與任何備轉服務",
    "answer": "B",
    "explanation": "抽蓄水力可在低負載時抽水、尖峰時發電，並支援調頻與備轉。",
    "source_title": "02. 電力交易平台參考資料－電力系統運轉與調度",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "抽蓄水力對系統貢獻",
    "is_active": true,
    "tags": "抽蓄水力;調頻;備轉"
  },
  {
    "id": "S1-010",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "電力市場",
    "level": "1基礎",
    "question": "在區域邊際價格（LMP）概念中，某電氣節點的 LMP 最接近下列哪一種意義？",
    "option_a": "該節點增加下一個 1 MW 所需增加的邊際成本",
    "option_b": "該節點所有機組的平均建置成本",
    "option_c": "用戶每月基本電費",
    "option_d": "再生能源憑證平均價格",
    "answer": "A",
    "explanation": "LMP 可理解為特定電氣節點再增加下一個 MW 所需增加的邊際成本。",
    "source_title": "03. 電力交易平台參考資料－電力交易市場概述",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "LMP 概念",
    "is_active": true,
    "tags": "LMP;邊際成本"
  },
  {
    "id": "S1-011",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "電力市場",
    "level": "2理解",
    "question": "在 LMP 架構下，負載區域（Load Zone）的價格通常如何形成？",
    "option_a": "取區域內所有負載點 LMP 的加權平均",
    "option_b": "固定採全國最低 LMP",
    "option_c": "只看最大機組報價",
    "option_d": "由用戶自行填寫",
    "answer": "A",
    "explanation": "負載區域價格可由區域內所有負載點的 LMP 加權平均形成。",
    "source_title": "03. 電力交易平台參考資料－電力交易市場概述",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "LMP 結算點",
    "is_active": true,
    "tags": "LMP;Load Zone"
  },
  {
    "id": "S1-012",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "平台架構",
    "level": "1基礎",
    "question": "台電電力交易平台目前開設的兩大市場為何？",
    "option_a": "日前輔助服務市場與備用容量市場",
    "option_b": "即時電能市場與碳權市場",
    "option_c": "綠電直購市場與零售市場",
    "option_d": "期貨市場與選擇權市場",
    "answer": "A",
    "explanation": "電力交易平台開設日前輔助服務市場與備用容量市場。",
    "source_title": "電力交易平台－關於平台",
    "source_url": "https://etp.taipower.com.tw/web/about",
    "source_locator": "官方平台介紹",
    "is_active": true,
    "tags": "平台架構;市場"
  },
  {
    "id": "S1-013",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "輔助服務商品",
    "level": "1基礎",
    "question": "下列何者不是日前輔助服務市場的交易商品？",
    "option_a": "調頻備轉容量",
    "option_b": "電能移轉複合動態調節備轉容量",
    "option_c": "即時備轉容量",
    "option_d": "綠電憑證容量",
    "answer": "D",
    "explanation": "現行商品包括調頻備轉、E-dReg、即時備轉及補充備轉。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "第4條",
    "is_active": true,
    "tags": "商品;日前輔助服務"
  },
  {
    "id": "S1-014",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "調頻備轉",
    "level": "1基礎",
    "question": "動態調頻（dReg）的基本作動方式為何？",
    "option_a": "每日一次人工調整",
    "option_b": "每秒追隨系統頻率，以 60 Hz 為基準執行調頻反應",
    "option_c": "僅在停電時啟動",
    "option_d": "只依電價高低充放電",
    "answer": "B",
    "explanation": "dReg 自動偵測系統頻率，並每秒追隨 60 Hz 基準的頻率變化。",
    "source_title": "07. 日前輔助服務市場之交易商品項目規格",
    "source_url": "https://etp.taipower.com.tw/web/download",
    "source_locator": "dReg 技術規格",
    "is_active": true,
    "tags": "dReg;60Hz"
  },
  {
    "id": "S1-015",
    "subject": "科目一｜電力系統與電力市場",
    "topic": "市場參與",
    "level": "2理解",
    "question": "欲參與日前輔助服務市場或備用容量市場，下列敘述何者正確？",
    "option_a": "只要註冊其中一個市場即可自動參與全部市場",
    "option_b": "兩個市場須分別辦理申請",
    "option_c": "完全不需註冊即可報價",
    "option_d": "只有國營業者可申請",
    "answer": "B",
    "explanation": "欲參與兩類市場者，應分別辦理申請。",
    "source_title": "電力交易平台－關於平台",
    "source_url": "https://etp.taipower.com.tw/web/about",
    "source_locator": "官方平台介紹",
    "is_active": true,
    "tags": "市場參與;註冊"
  },
  {
    "id": "S2-001",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "現行規範",
    "level": "1基礎",
    "question": "115 年資格測驗準備時，現行《電力交易平台管理規範及作業程序》最新版版次為何？",
    "option_a": "TPC-MT-v03",
    "option_b": "TPC-MT-v04",
    "option_c": "TPC-MT-v05",
    "option_d": "TPC-MT-v06",
    "answer": "C",
    "explanation": "目前最新版為 TPC-MT-v05，施行日為 114 年 10 月 1 日。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "版次 TPC-MT-v05",
    "is_active": true,
    "tags": "現行規範;版本"
  },
  {
    "id": "S2-002",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "市場運作",
    "level": "1基礎",
    "question": "依現行規範，日前輔助服務市場的運作原則為何？",
    "option_a": "每週營運一次",
    "option_b": "每月營運一次",
    "option_c": "以每日營運為原則",
    "option_d": "僅夏季營運",
    "answer": "C",
    "explanation": "日前輔助服務市場以每日營運為原則，特殊情況例外。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "第3條",
    "is_active": true,
    "tags": "市場運作;每日營運"
  },
  {
    "id": "S2-003",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "市場商品",
    "level": "1基礎",
    "question": "備用容量市場的交易商品為何？",
    "option_a": "調頻備轉容量",
    "option_b": "備用供電容量",
    "option_c": "即時電能",
    "option_d": "綠電憑證",
    "answer": "B",
    "explanation": "備用容量市場的交易商品為「備用供電容量」。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "第4條",
    "is_active": true,
    "tags": "備用容量市場;備用供電容量"
  },
  {
    "id": "S2-004",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "即時備轉",
    "level": "1基礎",
    "question": "即時備轉容量在收到調度指令後，應於多久內達到 100% 約定容量？",
    "option_a": "1 分鐘",
    "option_b": "5 分鐘",
    "option_c": "10 分鐘",
    "option_d": "30 分鐘",
    "answer": "C",
    "explanation": "即時備轉應於 10 分鐘內達到 100% 約定容量。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：即時備轉",
    "is_active": true,
    "tags": "即時備轉;10分鐘"
  },
  {
    "id": "S2-005",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "即時備轉",
    "level": "1基礎",
    "question": "即時備轉容量自調度指令下達後第 10 分鐘起，應持續服務多久？",
    "option_a": "15 分鐘",
    "option_b": "30 分鐘",
    "option_c": "60 分鐘",
    "option_d": "120 分鐘",
    "answer": "C",
    "explanation": "即時備轉自第 10 分鐘起，應具備持續執行 60 分鐘的能力。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：即時備轉",
    "is_active": true,
    "tags": "即時備轉;持續時間"
  },
  {
    "id": "S2-006",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "即時備轉",
    "level": "2理解",
    "question": "即時備轉完成一次調度服務後，應於多久內恢復待命？",
    "option_a": "30 分鐘",
    "option_b": "60 分鐘",
    "option_c": "120 分鐘",
    "option_d": "240 分鐘",
    "answer": "C",
    "explanation": "即時備轉的恢復時間為 120 分鐘內。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：即時備轉",
    "is_active": true,
    "tags": "即時備轉;恢復時間"
  },
  {
    "id": "S2-007",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "即時備轉",
    "level": "2理解",
    "question": "某交易資源的即時備轉完全反應時間為 2 分鐘，依現行規範其效能級數為何？",
    "option_a": "1 級",
    "option_b": "2 級",
    "option_c": "3 級",
    "option_d": "不具資格",
    "answer": "B",
    "explanation": "T≤1 分鐘為 1 級；1<T≤3 分鐘為 2 級；3<T≤5 分鐘為 3 級。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "表6-8",
    "is_active": true,
    "tags": "即時備轉;效能級數"
  },
  {
    "id": "S2-008",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "補充備轉",
    "level": "1基礎",
    "question": "補充備轉容量收到調度指令後，應於多久內達到 100% 得標容量？",
    "option_a": "5 分鐘",
    "option_b": "10 分鐘",
    "option_c": "20 分鐘",
    "option_d": "30 分鐘",
    "answer": "D",
    "explanation": "補充備轉應於 30 分鐘內達到 100% 得標容量。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：補充備轉",
    "is_active": true,
    "tags": "補充備轉;30分鐘"
  },
  {
    "id": "S2-009",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "補充備轉",
    "level": "1基礎",
    "question": "補充備轉容量達全反應後，至少應具備持續服務多久的能力？",
    "option_a": "30 分鐘",
    "option_b": "60 分鐘",
    "option_c": "90 分鐘",
    "option_d": "120 分鐘",
    "answer": "D",
    "explanation": "補充備轉持續服務時間至少為 120 分鐘。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：補充備轉",
    "is_active": true,
    "tags": "補充備轉;持續時間"
  },
  {
    "id": "S2-010",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "補充備轉",
    "level": "2理解",
    "question": "補充備轉完成一次調度服務後，應於多久內恢復待命？",
    "option_a": "60 分鐘",
    "option_b": "120 分鐘",
    "option_c": "180 分鐘",
    "option_d": "240 分鐘",
    "answer": "D",
    "explanation": "補充備轉恢復時間為 240 分鐘內。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：補充備轉",
    "is_active": true,
    "tags": "補充備轉;恢復時間"
  },
  {
    "id": "S2-011",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "E-dReg",
    "level": "1基礎",
    "question": "E-dReg 的電能移轉排程，每一排程指定期間原則上為多久？",
    "option_a": "5 分鐘",
    "option_b": "10 分鐘",
    "option_c": "15 分鐘",
    "option_d": "60 分鐘",
    "answer": "C",
    "explanation": "每一排程指定期間以 15 分鐘為原則。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：E-dReg",
    "is_active": true,
    "tags": "E-dReg;15分鐘"
  },
  {
    "id": "S2-012",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "E-dReg",
    "level": "1基礎",
    "question": "E-dReg 每次由電力調度單位下達的調度指令，指定期間原則上為多久？",
    "option_a": "1 分鐘",
    "option_b": "5 分鐘",
    "option_c": "15 分鐘",
    "option_d": "30 分鐘",
    "answer": "B",
    "explanation": "每次調度指令指定期間以 5 分鐘為原則。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：E-dReg",
    "is_active": true,
    "tags": "E-dReg;5分鐘"
  },
  {
    "id": "S2-013",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "E-dReg",
    "level": "2理解",
    "question": "E-dReg 執行電能移轉時，對排程或調度指令所指定容量的反應要求為何？",
    "option_a": "1 秒鐘內反應達指定容量",
    "option_b": "10 秒鐘內反應達指定容量",
    "option_c": "1 分鐘內反應達指定容量",
    "option_d": "無反應時間要求",
    "answer": "A",
    "explanation": "現行規範要求於所訂時點之 1 秒鐘內反應達指定容量。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：E-dReg",
    "is_active": true,
    "tags": "E-dReg;反應時間"
  },
  {
    "id": "S2-014",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "E-dReg",
    "level": "3情境",
    "question": "E-dReg 交易資源正在執行電能移轉「充電模式」，若系統頻率降至 59.50 Hz 以下，下列何者符合現行規範？",
    "option_a": "繼續原排程充電，不做任何變更",
    "option_b": "立即停止當下排程，取消次一 15 分鐘排程，改以動態調節模式執行 900 秒",
    "option_c": "永久退出市場",
    "option_d": "只降低 10% 充電量",
    "answer": "B",
    "explanation": "應停止當下排程、取消次一 15 分鐘排程，改以動態調節功能執行 900 秒，再恢復既定排程。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "附件六：E-dReg 同時執行",
    "is_active": true,
    "tags": "E-dReg;59.50Hz;情境"
  },
  {
    "id": "S2-015",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "sReg",
    "level": "2理解",
    "question": "靜態調頻備轉（sReg）在系統頻率降至 59.90 Hz（CF）時，主要反應要求為何？",
    "option_a": "停止提供服務",
    "option_b": "於數秒內開始反應，並於 10 秒內達得標容量 100%",
    "option_c": "30 分鐘內達 100%",
    "option_d": "僅需發出警報",
    "answer": "B",
    "explanation": "sReg 在 59.90 Hz（CF）時應數秒內開始反應，並於 10 秒內達得標容量 100%。",
    "source_title": "電力交易平台管理規範及作業程序",
    "source_url": "https://ea01.moeaea.gov.tw/c006/05/DownLoadList/download/248",
    "source_locator": "表6-4 sReg 技術規格",
    "is_active": true,
    "tags": "sReg;59.90Hz"
  }
];
