window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"H9-001","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜容量籌措","level":"2理解","question":"備用供電容量義務者可透過哪些方式籌措容量？","option_a":"自設機組、雙邊契約或電力交易平台備用容量市場","option_b":"只能向台電單一採購","option_c":"只能自設機組","option_d":"只能透過零售市場","answer":"A","explanation":"教材列示可採自設、雙邊交易，或於電力交易平台之備用容量市場籌措。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"義務者籌措供電容量之方式","is_active":true,"tags":"單元09;備用供電容量;籌措"},
{"id":"H9-002","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜市場時程","level":"2理解","question":"備用容量市場的市場流程中，何者出現在交易媒合期間之前？","option_a":"資訊閉鎖期","option_b":"成交紀錄公布後才開始","option_c":"違規處分期","option_d":"零售結算期","answer":"A","explanation":"教材市場總覽顯示自由刊登資訊、資訊閉鎖期，再進入交易媒合期間。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"市場總覽","is_active":true,"tags":"單元09;市場時程"},
{"id":"H9-003","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜交易媒合時間","level":"2情境","question":"依教材，當次媒合起始日起第6日至第10日主要是哪一方進行競價？","option_a":"買方","option_b":"賣方","option_c":"電力調度中心","option_d":"一般用戶","answer":"A","explanation":"教材列示：賣方前3日設定標售資訊，第4至5日審查，第6至10日為買方競價期間。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"交易媒合期間相關具體時間表","is_active":true,"tags":"單元09;交易媒合;競價"},
{"id":"H9-004","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜保證金計算","level":"3情境計算","question":"備用供電容量每MW應繳保證金為109,500元。若交易容量為3.2MW，且MW以下無條件進位至MW，應繳多少保證金？","option_a":"328,500元","option_b":"350,400元","option_c":"438,000元","option_d":"547,500元","answer":"C","explanation":"3.2MW無條件進位為4MW；4×109,500=438,000元。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"保證金收取方式","is_active":true,"tags":"單元09;計算;保證金"},
{"id":"H9-005","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜標售底價","level":"1基礎","question":"教材列示備用容量市場賣方標售底價上限為多少？","option_a":"50萬元/MW-年","option_b":"100萬元/MW-年","option_c":"200萬元/MW-年","option_d":"500萬元/MW-年","answer":"C","explanation":"教材列示標售底價不可超過新臺幣200萬元/MW。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"賣方標售資訊內容項目","is_active":true,"tags":"單元09;標售底價"},
{"id":"H9-006","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜市場比較","level":"2理解","question":"日前輔助服務市場與備用容量市場的交易機制，何者配對正確？","option_a":"日前輔助服務：最佳化排程競價；備用容量：交易媒合依出價高低決定得標順序","option_b":"兩者都只靠抽籤","option_c":"日前輔助服務只做雙邊契約；備用容量只做即時調度","option_d":"兩者完全沒有競價或媒合","answer":"A","explanation":"教材比較表指出日前輔助服務採競價並由最佳化排程分配；備用容量則採交易媒合，依出價高低決定得標順序。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"日前輔助服務市場與備用容量市場比較","is_active":true,"tags":"單元09;市場比較"},
{"id":"H9-007","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜成交紀錄","level":"2理解","question":"交易媒合期間終止後，買賣雙方最遲應於多久內回報議約結果及相關資訊？","option_a":"3日內","option_b":"5日內","option_c":"10日內","option_d":"30日內","answer":"C","explanation":"教材列示買賣雙方至遲於交易媒合期間終止日後10日內回報議約結果；台電於30日內彙整公布。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"交易媒合期間相關具體時間表","is_active":true,"tags":"單元09;成交紀錄;10日"},
{"id":"H9-008","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜交易容量","level":"1基礎","question":"教材中，備用容量市場交易資源的交易容量原則為何？","option_a":"至少10kW，基本交易單位10kW，且不得聚合","option_b":"至少1kW，可任意聚合","option_c":"至少1MW，只能以100MW為單位","option_d":"沒有最低容量限制","answer":"A","explanation":"教材列示交易容量按淨尖峰能力計算，須為10kW以上，基本交易單位10kW，且不得聚合。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"備用容量市場供給者之參與方式","is_active":true,"tags":"單元09;交易容量;10kW"}
]);