window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"H5-001","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜章節架構","level":"1基礎","question":"管理規範及作業程序中，註冊登記、保證金、參與費用、退出平台等內容主要屬於哪一章？","option_a":"第一章 總則","option_b":"第二章 平台參與","option_c":"第五章 市場管理與監視","option_d":"第八章 違規處理","answer":"B","explanation":"第二章「平台參與」涵蓋註冊登記、資訊正確性、保證金、參與費用、退出及註冊登記失效等。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"管理規範及作業程序大綱及對照表","is_active":true,"tags":"單元05;章節架構"},
{"id":"H5-002","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜註冊登記","level":"2理解","question":"非屬國營發電業者申請成為合格交易者，下列何者屬於教材列示的註冊程序？","option_a":"提交必要文件、通過能力測試、繳納保證金與參與費用、取得帳密","option_b":"只需繳交一張身分證即可","option_c":"先交易後再補文件","option_d":"完全不需能力測試","answer":"A","explanation":"教材列示申請文件、能力測試、保證金與參與費用，以及取得市場管理系統帳密等步驟。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第二章平台參與－第七條","is_active":true,"tags":"單元05;註冊登記"},
{"id":"H5-003","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜專業人員證明","level":"1基礎","question":"附件一列示，若以自有資源模式參與，應具幾張電力交易平台專業人員資格證明？","option_a":"1張","option_b":"2張","option_c":"3張","option_d":"5張","answer":"A","explanation":"教材附件一列示：自有資源1張；代理資源3張專業人員資格證明。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"附件一 註冊登記程序","is_active":true,"tags":"單元05;專業人員;註冊"},
{"id":"H5-004","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜保證金","level":"2情境","question":"合格交易者的保證金不足，收到電力交易單位通知後，原則上應於次日起多久內補足？","option_a":"3個工作日","option_b":"5個工作日","option_c":"10個工作日","option_d":"30日","answer":"B","explanation":"第十條規定，保證金不足時應於通知次日起五個工作日內補足。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第二章平台參與－第十條保證金規範","is_active":true,"tags":"單元05;保證金"},
{"id":"H5-005","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜註冊失效","level":"2理解","question":"下列哪一情況達連續180日，教材列為得註銷註冊登記的情形之一？","option_a":"保證金不足額","option_b":"單日未登入網站","option_c":"一週未開會","option_d":"一次填錯密碼","answer":"A","explanation":"第十三條列示，保證金不足額期間連續達180日者，得註銷相關註冊登記。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第二章平台參與－第十三條註冊登記失效","is_active":true,"tags":"單元05;註冊失效;180日"},
{"id":"H5-006","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜資源聚合","level":"2情境","question":"申請註冊的參與資源容量低於100kW時，依教材應如何處理才能作為單一資源進行能力測試？","option_a":"至少聚合同類型資源達100kW","option_b":"直接免測試","option_c":"至少達10kW即可","option_d":"只能永久退出市場","answer":"A","explanation":"第十五條規定，低於100kW者應至少聚合同類型資源達100kW，始得視為單一資源測試。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第三章日前輔助服務市場－第十五條","is_active":true,"tags":"單元05;聚合;100kW"},
{"id":"H5-007","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜爭議處理","level":"2理解","question":"平台交易爭議先經電力交易單位溝通仍未解決，下一步較符合教材程序的是？","option_a":"直接永久停權","option_b":"由學者專家協調會進行協調","option_c":"自動視為買方勝訴","option_d":"立即取消所有交易","answer":"B","explanation":"爭議可先由電力交易單位溝通協商；仍未解決時，由學者專家協調會協調。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第七章爭議處理機制－第三十五條","is_active":true,"tags":"單元05;爭議處理"},
{"id":"H5-008","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜違規處理","level":"2情境","question":"備用容量市場買賣方未依交易媒合結果締約，依教材可能受到何種處分？","option_a":"二年內不得參與備用容量市場","option_b":"僅口頭提醒","option_c":"提高每日報價上限","option_d":"自動取得下一次優先資格","answer":"A","explanation":"第四十條規定，特定違反備用容量市場管理規範情形，二年內不得參與備用容量市場。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第八章違規處理－第四十條","is_active":true,"tags":"單元05;違規處理;二年"}
]);