window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat(
[
  {
    "id": "HV05-001",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜管理規範架構",
    "level": "2理解",
    "cognitive": "分類",
    "question": "下列哪一組最符合教材所述「電力交易平台管理規範及作業程序」的現行架構？",
    "option_a": "九章、42條、13個附件",
    "option_b": "八章、40條、10個附件",
    "option_c": "九章、36條、13個附件",
    "option_d": "十章、42條、15個附件",
    "answer": "A",
    "explanation": "教材說明最新版管理規範分為九章，共42條條文及13個附件。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "貳、管理規範及作業程序－架構總覽",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;管理規範;章節"
  },
  {
    "id": "HV05-002",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜保證金補足",
    "level": "3情境",
    "cognitive": "期限辨識",
    "question": "某合格交易者收到台電通知，其保證金已不足額。下列處理何者符合教材？",
    "option_a": "自通知次日起5個工作日內補足",
    "option_b": "自通知日起10個日曆日內補足",
    "option_c": "可等到180日屆滿前再補",
    "option_d": "下次投標前補足即可",
    "answer": "A",
    "explanation": "保證金不足時，應於電力交易單位通知之次日起5個工作日內補足。180日是另一個可能導致註冊失效的期間，不是補繳期限。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第十條【保證金規範】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;5個工作日;保證金;易混淆"
  },
  {
    "id": "HV05-003",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜註冊登記失效",
    "level": "3情境",
    "cognitive": "期限辨識",
    "question": "某合格交易者保證金不足額已連續179日，隔日仍未補足。依教材，下列何者最適當？",
    "option_a": "達連續180日後，電力交易單位得註銷相關註冊登記",
    "option_b": "第180日會自動永久停權且不得恢復",
    "option_c": "只會加收參與費，不影響註冊",
    "option_d": "必須等滿一年才能處理",
    "answer": "A",
    "explanation": "教材第十三條列明：保證金不足額期間連續達180日者，電力交易單位得註銷合格交易者、報價代碼或交易資源之註冊登記。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第十三條【註冊登記失效】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;180日;註冊失效"
  },
  {
    "id": "HV05-004",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜註冊登記失效",
    "level": "3情境",
    "cognitive": "條件辨識",
    "question": "參與日前輔助服務市場者，若長期未報價或被暫停報價權限，達到何種情況可能構成註冊登記失效事由？",
    "option_a": "連續達180日",
    "option_b": "累計達30日",
    "option_c": "連續達5個工作日",
    "option_d": "任何一天未報價即失效",
    "answer": "A",
    "explanation": "教材第十三條將「未報價或經暫停報價權限連續達180日」列為得註銷註冊登記的情形之一。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第十三條【註冊登記失效】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;180日;未報價"
  },
  {
    "id": "HV05-005",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜日前市場保證金",
    "level": "3情境",
    "cognitive": "公式理解",
    "question": "日前輔助服務市場的保證金額度，教材所列計算基礎為何？",
    "option_a": "參與容量總額 × 每千瓩應繳保證金金額",
    "option_b": "成交價 × 年發電量",
    "option_c": "裝置容量 × 市場最高價格",
    "option_d": "參與容量 × 參與費月費",
    "answer": "A",
    "explanation": "第十條規定日前輔助服務市場保證金額度＝參與容量總額×每千瓩應繳保證金金額。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第十條【保證金規範】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;保證金;公式"
  },
  {
    "id": "HV05-006",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜備用容量市場保證金",
    "level": "3情境",
    "cognitive": "市場比較",
    "question": "關於備用容量市場保證金，下列何者符合教材？",
    "option_a": "資訊閉鎖期間開始後10日內繳納，參與容量總額以千瓩為最小單位、以下無條件進位",
    "option_b": "註冊當日一定繳納，容量一律以10kW為保證金計算最小單位",
    "option_c": "成交後30日內繳納，容量小數一律捨去",
    "option_d": "只要是買方就永遠免繳保證金",
    "answer": "A",
    "explanation": "管理規範指出，備用容量市場保證金應於資訊閉鎖期間開始後10日內繳納，且保證金計算的參與容量總額以千瓩為最小單位，千瓩以下部分無條件進位。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第十條【保證金規範】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;10日;千瓩;備用容量;易混淆"
  },
  {
    "id": "HV05-007",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜專業人員證明",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "甲公司以自有資源參與，乙公司代理其他資源參與。申請合格交易者時，專業人員資格證明最低需求如何配對？",
    "option_a": "甲1張、乙3張",
    "option_b": "甲3張、乙1張",
    "option_c": "兩者皆1張",
    "option_d": "兩者皆3張",
    "answer": "A",
    "explanation": "附件一列明：自有資源1張，代理資源3張。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "附件一【註冊登記程序】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;自有資源;代理資源;1張;3張"
  },
  {
    "id": "HV05-008",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜爭議處理",
    "level": "3情境",
    "cognitive": "程序順序",
    "question": "交易爭議先與電力交易單位溝通協商仍無法解決，依教材下一階段為何？",
    "option_a": "由學者專家協調會進行協調",
    "option_b": "直接由法院強制判決",
    "option_c": "由賣方自行宣布結果",
    "option_d": "立即註銷雙方註冊",
    "answer": "A",
    "explanation": "教材爭議處理機制為先溝通協商；仍未解決，再由學者專家協調會進行協調。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第七章【爭議處理機制】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;爭議;程序"
  },
  {
    "id": "HV05-009",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜備用容量違規",
    "level": "3情境",
    "cognitive": "後果辨識",
    "question": "備用容量市場買賣方未依交易媒合結果締約，依教材可能產生哪一組後果？",
    "option_a": "二年內不得參與備用容量市場，且台電得不予發還保證金",
    "option_b": "僅口頭提醒，不影響市場參與",
    "option_c": "永久不得參與任何電力市場，且必然沒收全部資產",
    "option_d": "只需補繳參與費即可",
    "answer": "A",
    "explanation": "第四十條規定特定違規情形二年內不得參與備用容量市場；未依媒合結果締約者，台電得不予發還保證金。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "第四十條【違反備用容量市場相關管理規範】",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;二年;保證金;違規"
  },
  {
    "id": "HV05-010",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第5單元｜章節辨識",
    "level": "2理解",
    "cognitive": "分類",
    "question": "下列哪一主題最應在管理規範的「第三章 日前輔助服務市場」中尋找，而不是第四章備用容量市場？",
    "option_a": "商品規格、能力測試及聚合、報價與最佳化排程",
    "option_b": "備用容量商品之交易媒合與競標出價",
    "option_c": "學者專家協調會組成",
    "option_d": "市場異常監視與減緩措施",
    "answer": "A",
    "explanation": "教材大綱將日前輔助服務市場的商品規格、能力測試與聚合、報價、最佳化排程、結清與結算等列在第三章。",
    "source_title": "05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽",
    "source_url": "",
    "source_locator": "管理規範大綱及對照表",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元05;已核對;高鑑別;章節;日前市場"
  },
  {
    "id": "HV06-001",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜專業人員資格",
    "level": "3情境",
    "cognitive": "程序辨識",
    "question": "某人筆試通過後就自稱已取得「電力交易平台專業人員資格證明」。依教材，哪一點有問題？",
    "option_a": "還需由平台成員舉薦並完成上機訓練，之後才核發資格證明",
    "option_b": "還需再參加一次相同筆試",
    "option_c": "必須先成為公司負責人",
    "option_d": "筆試合格通知本身就是永久資格證明",
    "answer": "A",
    "explanation": "教材區分筆試合格通知與正式資格證明；合格者須在期限內由申請參與市場註冊登記的平台成員舉薦並接受上機訓練。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "專業人員資格證明取得程序",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;筆試;上機訓練;資格證明"
  },
  {
    "id": "HV06-002",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜專業人員資格",
    "level": "2理解",
    "cognitive": "角色辨識",
    "question": "依教材，電力交易平台專業人員與合格交易者的關係何者正確？",
    "option_a": "專業人員應為合格交易者之受僱人",
    "option_b": "專業人員必須是台電員工",
    "option_c": "專業人員只能是公司負責人",
    "option_d": "兩者不得存在僱傭關係",
    "answer": "A",
    "explanation": "教材明列電力交易平台專業人員應為合格交易者之受僱人。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "註冊登記程序－電力交易平台專業人員資格證明",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;受僱人;專業人員"
  },
  {
    "id": "HV06-003",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜註冊程序",
    "level": "3情境",
    "cognitive": "程序順序",
    "question": "下列哪一流程最接近教材所示的合格交易者註冊程序？",
    "option_a": "書面申請與審查→專業人員資格→通訊能力測試→執行能力測試→繳交保證金／核發帳號→完成註冊",
    "option_b": "先核發正式帳號→再書面審查→最後測試",
    "option_c": "先繳成交價→直接註冊→日後再補測試",
    "option_d": "只要有專業人員資格即可跳過其他程序",
    "answer": "A",
    "explanation": "教材程序總覽依序呈現書面審查、取得專業人員資格、通訊能力測試、執行能力測試、繳交保證金／核發帳號及註冊完成。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "註冊登記程序總覽",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;註冊;程序"
  },
  {
    "id": "HV06-004",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜能力測試",
    "level": "3情境",
    "cognitive": "概念比較",
    "question": "通訊能力測試與輔助服務執行能力測試的目的，何者配對正確？",
    "option_a": "前者確認資訊介接符合通訊規格；後者確認資源符合交易商品技術規格",
    "option_b": "前者測電價；後者測公司信用",
    "option_c": "前者測發票；後者測帳戶餘額",
    "option_d": "兩者目的完全相同，只是名稱不同",
    "answer": "A",
    "explanation": "教材明確區分兩類能力檢測：通訊能力測試確認遙測通訊資訊介接；執行能力測試確認資源符合商品技術規格。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "參、能力測試程序－前言",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;通訊測試;執行能力測試"
  },
  {
    "id": "HV06-005",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜通訊能力",
    "level": "2理解",
    "cognitive": "規格辨識",
    "question": "教材列示通訊能力測試的通訊協定類型可擇一採用何者？",
    "option_a": "IEC 61850 或 DNP 3.0",
    "option_b": "HTTP 或 FTP，只限這兩種",
    "option_c": "Bluetooth 或 NFC",
    "option_d": "SMTP 或 POP3",
    "answer": "A",
    "explanation": "教材列出IEC 61850與DNP 3.0兩類通訊協定要求。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "通訊能力測試要求",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;IEC61850;DNP3.0"
  },
  {
    "id": "HV06-006",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜保證金",
    "level": "3情境",
    "cognitive": "市場比較",
    "question": "哪一敘述正確區分日前輔助服務市場與備用容量市場的保證金繳納者？",
    "option_a": "日前市場由各交易商品賣方繳納；備用容量市場參與交易媒合時買方及賣方均繳納",
    "option_b": "兩個市場都只有買方繳納",
    "option_c": "兩個市場都只有賣方繳納",
    "option_d": "兩個市場均免保證金",
    "answer": "A",
    "explanation": "教材明列日前輔助服務市場保證金由各交易商品賣方繳納；備用容量市場則由參與交易媒合之買方及賣方繳納。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "註冊登記及資訊變更程序－保證金",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;保證金;買方;賣方"
  },
  {
    "id": "HV06-007",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜保證金金額",
    "level": "3情境計算",
    "cognitive": "數字辨識",
    "question": "某資源以1MW參與即時備轉。依教材附件四，每MW應繳保證金為何？",
    "option_a": "153,300元",
    "option_b": "197,100元",
    "option_c": "109,500元",
    "option_d": "1,000元",
    "answer": "A",
    "explanation": "教材價格表列示即時備轉每MW應繳保證金153,300元。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "保證金－附件四價格表",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;即時備轉;153300"
  },
  {
    "id": "HV06-008",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜保證金金額",
    "level": "3情境",
    "cognitive": "易混淆數字",
    "question": "下列哪一組商品的每MW應繳保證金金額相同，且均為197,100元？",
    "option_a": "調頻備轉與E-dReg",
    "option_b": "即時備轉與補充備轉",
    "option_c": "E-dReg與備用供電容量",
    "option_d": "補充備轉與調頻備轉",
    "answer": "A",
    "explanation": "教材附件四列示調頻備轉與E-dReg均為197,100元/MW。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "保證金－附件四價格表",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;197100;調頻備轉;E-dReg"
  },
  {
    "id": "HV06-009",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜退出市場",
    "level": "3情境",
    "cognitive": "期限辨識",
    "question": "申請退出市場時，若台電通知補正資料後逾多久仍未補正，教材說明案件視為終止申請？",
    "option_a": "90日",
    "option_b": "5個工作日",
    "option_c": "30日",
    "option_d": "180日",
    "answer": "A",
    "explanation": "退出市場流程註記：通知補正資料逾90日未補正者，案件視為終止申請。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "退出市場流程",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;90日;退出"
  },
  {
    "id": "HV06-010",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第6單元｜低於100kW聚合資源",
    "level": "2理解",
    "cognitive": "文件辨識",
    "question": "日前輔助服務市場若申報低於100kW之聚合資源，教材列出的對應交易資源資訊表為何？",
    "option_a": "表格3-1B",
    "option_b": "表格1-1",
    "option_c": "表格2-1",
    "option_d": "表格5",
    "answer": "A",
    "explanation": "教材應檢附文件表列示表格3-1B為「交易資源資訊表（日前輔助服務市場，低於100kW之聚合資源）」。",
    "source_title": "06. 電力交易平台參考資料 日前輔助服務市場之參與作法",
    "source_url": "",
    "source_locator": "應檢附文件－註冊登記申請書",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元06;已核對;高鑑別;100kW;3-1B;文件"
  },
  {
    "id": "HV07-001",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜dReg",
    "level": "3情境",
    "cognitive": "商品辨識",
    "question": "某儲能資源可自動偵測頻率，依既定運轉曲線雙向作動，並在1秒內達100%充放電。最符合哪一商品？",
    "option_a": "dReg",
    "option_b": "sReg",
    "option_c": "即時備轉",
    "option_d": "補充備轉",
    "answer": "A",
    "explanation": "教材結語將dReg定義為具雙向頻率提升能力，可在1秒內快速反應100%充放電。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "肆、結語－dReg",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;dReg;1秒;雙向"
  },
  {
    "id": "HV07-002",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜sReg",
    "level": "3情境",
    "cognitive": "商品辨識",
    "question": "某需量反應資源在系統頻率降至59.90Hz時，可於10秒內達100%輸出功率。最符合哪一商品？",
    "option_a": "sReg",
    "option_b": "dReg",
    "option_c": "E-dReg",
    "option_d": "補充備轉",
    "answer": "A",
    "explanation": "教材結語指出sReg屬單向頻率提升能力，系統頻率達59.90Hz時應於10秒內達100%輸出。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "肆、結語－sReg",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;sReg;59.90Hz;10秒"
  },
  {
    "id": "HV07-003",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜E-dReg",
    "level": "3情境",
    "cognitive": "功能辨識",
    "question": "E-dReg除了執行動態調節外，還必須協助執行什麼？",
    "option_a": "尖離峰電能移轉",
    "option_b": "年度容量義務核定",
    "option_c": "燃料採購",
    "option_d": "輸電線檢修",
    "answer": "A",
    "explanation": "教材結語明列E-dReg除執行動態調節外，亦須協助執行尖離峰電能移轉。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "肆、結語－E-dReg",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;E-dReg;電能移轉"
  },
  {
    "id": "HV07-004",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜即時備轉",
    "level": "3情境",
    "cognitive": "時間條件",
    "question": "某資源在調度指令下達後第8分鐘達得標容量，並從第10分鐘起維持60分鐘。依教材時間規格，最符合哪一商品？",
    "option_a": "即時備轉",
    "option_b": "補充備轉",
    "option_c": "sReg",
    "option_d": "E-dReg",
    "answer": "A",
    "explanation": "即時備轉須在指令下達後10分鐘內達得標容量，並自第10分鐘起持續服務60分鐘。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "肆、結語－即時備轉",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;10分鐘;60分鐘"
  },
  {
    "id": "HV07-005",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜補充備轉",
    "level": "3情境",
    "cognitive": "時間條件",
    "question": "某資源需25分鐘才能達得標容量，但可維持130分鐘。依教材時間規格，最可能符合哪一商品？",
    "option_a": "補充備轉",
    "option_b": "即時備轉",
    "option_c": "dReg",
    "option_d": "sReg",
    "answer": "A",
    "explanation": "補充備轉要求30分鐘內達得標容量，並至少持續120分鐘；25分鐘與130分鐘符合該時間門檻。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "肆、結語－補充備轉",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;30分鐘;120分鐘"
  },
  {
    "id": "HV07-006",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜dReg與sReg比較",
    "level": "3情境",
    "cognitive": "比較",
    "question": "下列何者最能正確區分dReg與sReg？",
    "option_a": "dReg偏雙向且1秒反應；sReg偏單向且10秒反應",
    "option_b": "dReg只能單向且30分鐘反應；sReg雙向且1秒反應",
    "option_c": "兩者反應時間與方向完全相同",
    "option_d": "dReg只做容量市場；sReg只做售電",
    "answer": "A",
    "explanation": "教材結語明確區分dReg雙向、1秒與sReg單向、10秒。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "肆、結語－dReg與sReg",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;易混淆;1秒;10秒"
  },
  {
    "id": "HV07-007",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜E-dReg升降載",
    "level": "3情境",
    "cognitive": "程序理解",
    "question": "E-dReg每15分鐘取得新的電能移轉排程目標值時，教材要求資源如何調整？",
    "option_a": "區間開始即以等斜率升／降載，於第5分鐘達到目標值",
    "option_b": "第15分鐘才瞬間跳到目標值",
    "option_c": "前10分鐘完全不動，最後5分鐘任意調整",
    "option_d": "只要整小時平均達標即可",
    "answer": "A",
    "explanation": "教材E-dReg升降載率設定要求每15分鐘排程區間開始即以等斜率調整，於第5分鐘達到目標值。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "E-dReg升降載率設定",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;15分鐘;第5分鐘;E-dReg"
  },
  {
    "id": "HV07-008",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜E-dReg儲能規格",
    "level": "3情境計算",
    "cognitive": "規格計算",
    "question": "某併網型儲能要以3MW參與E-dReg。若只看教材「儲能電能量至少為參與容量2.5倍」的要求，最低需多少MWh？",
    "option_a": "7.5MWh",
    "option_b": "3MWh",
    "option_c": "5MWh",
    "option_d": "1.5MWh",
    "answer": "A",
    "explanation": "3MW×2.5＝7.5MWh。這是官方倍率規則的直接計算。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "併網型儲能設備參與E-dReg",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;2.5倍;計算"
  },
  {
    "id": "HV07-009",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜dReg儲能規格",
    "level": "3情境計算",
    "cognitive": "規格計算",
    "question": "某併網型儲能要以6MW參與dReg。若依教材「儲能電能量至少為參與容量0.5倍」的要求，最低需多少MWh？",
    "option_a": "3MWh",
    "option_b": "6MWh",
    "option_c": "15MWh",
    "option_d": "0.5MWh",
    "answer": "A",
    "explanation": "6MW×0.5＝3MWh。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "併網型儲能設備參與dReg",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;0.5倍;計算"
  },
  {
    "id": "HV07-010",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第7單元｜併網型儲能參與限制",
    "level": "3情境",
    "cognitive": "限制辨識",
    "question": "某非台電建置的併網型儲能已完成併網審查，業者希望參與補充備轉。依教材現行態樣說明，下列何者正確？",
    "option_a": "教材標示併網型儲能暫不開放參與補充備轉服務",
    "option_b": "只要容量達1MW即可參與補充備轉",
    "option_c": "僅台電自建儲能才可參與平台",
    "option_d": "併網型儲能只能參與備用容量市場",
    "answer": "A",
    "explanation": "教材併網型儲能態樣說明明列「暫不開放參與補充備轉服務」。",
    "source_title": "07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格",
    "source_url": "",
    "source_locator": "併網型儲能設備態樣說明",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元07;已核對;高鑑別;儲能;補充備轉;限制"
  },
  {
    "id": "HV08-001",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜市場時程",
    "level": "3情境",
    "cognitive": "時間辨識",
    "question": "某交易者11:05才送出當日報價。依教材每日時程，主要問題為何？",
    "option_a": "已超過11時報價截止時點",
    "option_b": "尚未到16時所以完全不影響",
    "option_c": "報價截止是午夜24時",
    "option_d": "只有備用容量市場才有截止時間",
    "answer": "A",
    "explanation": "日前輔助服務市場每日報價截止時點為11時。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;11時;報價截止"
  },
  {
    "id": "HV08-002",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜市場時程",
    "level": "3情境",
    "cognitive": "時間辨識",
    "question": "交易者想知道日前輔助服務市場當日競價結果，依教材通常何時公布？",
    "option_a": "16時",
    "option_b": "11時",
    "option_c": "9時",
    "option_d": "隔日8時",
    "answer": "A",
    "explanation": "教材結語明列16時公布競價結果。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;16時;競價結果"
  },
  {
    "id": "HV08-003",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜報價代碼",
    "level": "3情境",
    "cognitive": "限制辨識",
    "question": "某報價代碼想同時混合不同類型資源，並同時參與兩種輔助服務商品。依教材何者正確？",
    "option_a": "不符合；報價代碼僅得以同類型資源參與一項輔助服務商品",
    "option_b": "完全符合，報價代碼沒有資源類型限制",
    "option_c": "只要容量低於1MW就可混合",
    "option_d": "只要是同一家公司即可任意混合",
    "answer": "A",
    "explanation": "教材指出報價代碼為投標、結清、結算及調度依據，僅得以同類型資源參與一項輔助服務商品。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語－報價代碼",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;報價代碼;同類型;一項商品"
  },
  {
    "id": "HV08-004",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜交易容量",
    "level": "3情境",
    "cognitive": "門檻辨識",
    "question": "某報價代碼的交易容量為0.9MW。依教材結語所列原則，下列何者正確？",
    "option_a": "未達「交易容量需大於1MW」的要求",
    "option_b": "剛好符合，因0.9約等於1",
    "option_c": "只有補充備轉需要超過1MW",
    "option_d": "交易容量沒有門檻",
    "answer": "A",
    "explanation": "教材結語明列交易容量需大於1MW，並記至小數點後第一位。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語－報價代碼",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;1MW;交易容量"
  },
  {
    "id": "HV08-005",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜調頻備轉結算",
    "level": "3情境",
    "cognitive": "組成辨識",
    "question": "調頻備轉結算價金的組成，下列何者最符合教材？",
    "option_a": "容量費＋效能費＋服務品質指標",
    "option_b": "容量費＋電能服務費",
    "option_c": "只有電能費",
    "option_d": "容量費＋電能費，不含效能費",
    "answer": "A",
    "explanation": "教材結語列示調頻備轉結算價金包含容量費、效能費、服務品質指標。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語－結算價金",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;調頻備轉;結算"
  },
  {
    "id": "HV08-006",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜E-dReg結算",
    "level": "3情境",
    "cognitive": "組成辨識",
    "question": "哪一商品的結算價金包含「容量費、效能費、服務品質指標、電能服務費」？",
    "option_a": "E-dReg",
    "option_b": "補充備轉",
    "option_c": "備用供電容量",
    "option_d": "一般零售電價",
    "answer": "A",
    "explanation": "教材明列E-dReg結算包含容量費、效能費、服務品質指標與電能服務費。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語－結算價金",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;E-dReg;電能服務費"
  },
  {
    "id": "HV08-007",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜即時備轉結算",
    "level": "3情境",
    "cognitive": "組成辨識",
    "question": "即時備轉與補充備轉的結算組成有一個重要差異，何者正確？",
    "option_a": "即時備轉包含效能費；補充備轉不列效能費",
    "option_b": "補充備轉包含效能費；即時備轉不列效能費",
    "option_c": "兩者都只有容量費",
    "option_d": "兩者都只收電能服務費",
    "answer": "A",
    "explanation": "教材列示即時備轉包含容量費、效能費、服務品質指標、電能費；補充備轉包含容量費、服務品質指標、電能費。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "柒、結語－結算價金",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;即時備轉;補充備轉;效能費"
  },
  {
    "id": "HV08-008",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜最佳化結清",
    "level": "3情境",
    "cognitive": "機制理解",
    "question": "某交易者認為「只要我的報價最低，就一定直接得標」。依教材對市場結清的說明，何者正確？",
    "option_a": "不一定；平台以電能與輔助服務共同最佳化，在多項限制下決定資源分配",
    "option_b": "正確，平台只按單一報價由低到高排序",
    "option_c": "正確，且不考慮機組運轉限制",
    "option_d": "只要是民間資源就不參與最佳化",
    "answer": "A",
    "explanation": "平台採電能與輔助服務共同最佳化，MILP會考量電能成本、輔助服務成本、啟動成本與機組運轉限制等，不是單純按單一報價決定。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "市場結清之決定方式－最佳化作業",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;共同最佳化;MILP"
  },
  {
    "id": "HV08-009",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜結清價格",
    "level": "3情境",
    "cognitive": "機制理解",
    "question": "在最佳化作業決定得標資源後，教材說明結清價格如何形成？",
    "option_a": "以得標資源之最高報價價格作為結清價格",
    "option_b": "永遠取所有報價平均值",
    "option_c": "永遠取最低報價",
    "option_d": "由買方事後任意指定",
    "answer": "A",
    "explanation": "教材說明平台先透過最佳化決定得標結果，再以得標資源之最高報價價格作為結清價格。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "市場結清之決定方式－最佳化作業",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;結清價格;最高得標報價"
  },
  {
    "id": "HV08-010",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第8單元｜E-dReg電能服務費",
    "level": "3情境",
    "cognitive": "細節辨識",
    "question": "E-dReg某得標小時的電能服務費計算，教材將該小時切成幾個區間？",
    "option_a": "4個、每個15分鐘",
    "option_b": "6個、每個10分鐘",
    "option_c": "12個、每個5分鐘",
    "option_d": "2個、每個30分鐘",
    "answer": "A",
    "explanation": "教材將E-dReg得標小時分成4個各15分鐘區間計算電能服務費。",
    "source_title": "08. 電力交易平台參考資料 日前輔助服務市場之運作",
    "source_url": "",
    "source_locator": "E-dReg月結算價金－電能服務費",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元08;已核對;高鑑別;4區間;15分鐘"
  },
  {
    "id": "HV09-001",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜買賣方資格",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "備用容量市場中，下列哪一組角色配對最符合教材？",
    "option_a": "買方為備用供電容量義務者；賣方為備用容量市場供給者",
    "option_b": "買方固定為一般家庭；賣方固定為台電",
    "option_c": "買方為任何儲能設備；賣方為所有用戶",
    "option_d": "市場只有賣方沒有買方",
    "answer": "A",
    "explanation": "教材市場總覽將買方定位為備用供電容量義務者，賣方為備用容量市場供給者。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "貳、參與者資格與註冊登記－市場總覽",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;買方;賣方"
  },
  {
    "id": "HV09-002",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜賣方註冊",
    "level": "3情境",
    "cognitive": "資格辨識",
    "question": "備用容量市場賣方申請參與時，下列何者為教材明列要求？",
    "option_a": "需備1張電力交易平台專業人員資格證明，且僅得以自有資源模式參與",
    "option_b": "需備3張資格證明且只能代理資源",
    "option_c": "不需任何資源運轉特性資料",
    "option_d": "只要買方同意即可免註冊",
    "answer": "A",
    "explanation": "教材列示賣方需提交資源相關文件、1張專業人員資格證明，並僅得以自有資源模式參與。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "備用容量市場供給者之參與方式",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;1張;自有資源;賣方"
  },
  {
    "id": "HV09-003",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜買方專業人員",
    "level": "3情境",
    "cognitive": "角色辨識",
    "question": "備用容量市場買方在專業人員資格證明方面，教材如何規定？",
    "option_a": "無須提供專業人員資格證明",
    "option_b": "必須提供3張",
    "option_c": "必須提供1張且只能是公司負責人",
    "option_d": "必須提供5張",
    "answer": "A",
    "explanation": "教材明列備用容量市場買方無須提供專業人員資格證明。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "備用容量市場重要義務／參與資格",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;買方;免專業人員"
  },
  {
    "id": "HV09-004",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜交易容量",
    "level": "3情境",
    "cognitive": "門檻辨識",
    "question": "某賣方想以25kW資源參與備用容量市場。依教材交易容量規則，何者正確？",
    "option_a": "容量門檻符合至少10kW；交易基本單位為10kW，且不得聚合",
    "option_b": "因不足1MW所以完全不得參與",
    "option_c": "可與其他資源任意聚合後以1kW為單位交易",
    "option_d": "交易容量只能是100kW整數倍",
    "answer": "A",
    "explanation": "教材規定交易容量按淨尖峰能力計算，須10kW含以上，交易基本單位10kW，且不得聚合。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "備用容量市場供給者之參與方式",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;10kW;不得聚合"
  },
  {
    "id": "HV09-005",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜參與費用",
    "level": "3情境計算",
    "cognitive": "費用理解",
    "question": "備用容量市場某平台成員交易容量為1.2MW。依教材「MW以下無條件進位至MW」與年費1,000元/MW，系統使用年費應以幾MW計？",
    "option_a": "2MW",
    "option_b": "1MW",
    "option_c": "1.2MW精確計費",
    "option_d": "12MW",
    "answer": "A",
    "explanation": "教材指出交易容量以MW計，MW以下無條件進位至MW，因此1.2MW按2MW計。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "參與費用",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;1000元/MW;進位"
  },
  {
    "id": "HV09-006",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜需求量公告",
    "level": "3情境",
    "cognitive": "期限辨識",
    "question": "備用容量交易專區的需求量，教材規定原則上在當次媒合開始日前多久公告？",
    "option_a": "3日",
    "option_b": "10日",
    "option_c": "30日",
    "option_d": "1日",
    "answer": "A",
    "explanation": "教材時間表列明在當次媒合開始日前3日公告備用供電容量需求數量。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "交易媒合期間相關具體時間表",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;3日;需求公告"
  },
  {
    "id": "HV09-007",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜媒合時程",
    "level": "3情境",
    "cognitive": "程序順序",
    "question": "當次媒合起始後，下列時程排列何者正確？",
    "option_a": "第1～3日賣方設定標售資訊；第4～5日審查；第6～10日買方競價",
    "option_b": "第1～5日買方競價；第6～8日賣方設定；第9～10日審查",
    "option_c": "第1日審查；第2～10日皆為買方競價",
    "option_d": "三階段沒有固定順序",
    "answer": "A",
    "explanation": "教材具體時間表即為1～3日設定標售資訊、4～5日審查、6～10日買方競價。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "交易媒合期間相關具體時間表",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;1-3日;4-5日;6-10日"
  },
  {
    "id": "HV09-008",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜成交紀錄",
    "level": "3情境",
    "cognitive": "期限比較",
    "question": "交易媒合期間終止後，買賣雙方回報議約結果與台電彙整公布成交紀錄的期限分別為何？",
    "option_a": "10日內、30日內",
    "option_b": "30日內、10日內",
    "option_c": "5個工作日內、180日內",
    "option_d": "兩者都為3日內",
    "answer": "A",
    "explanation": "教材規定買賣雙方至遲於媒合終止後10日內回報；台電於終止後30日內彙整公布。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "交易媒合期間相關具體時間表",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;10日;30日;成交紀錄"
  },
  {
    "id": "HV09-009",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜重要義務",
    "level": "3情境",
    "cognitive": "重複交易辨識",
    "question": "某一容量已作為義務者應備總供電容量的一部分，賣方又想把同一容量拿到交易專區出售。依教材何者正確？",
    "option_a": "不得重複交易",
    "option_b": "只要價格較高即可再次出售",
    "option_c": "只要更換資源名稱即可",
    "option_d": "可重複出售一次",
    "answer": "A",
    "explanation": "教材重要義務明列同一單位容量不得重複交易。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "備用容量市場重要義務",
    "verification": "A-direct",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;不得重複交易"
  },
  {
    "id": "HV09-010",
    "subject": "科目二｜電力交易平台市場規則",
    "topic": "第9單元｜買方超買限制",
    "level": "3情境",
    "cognitive": "多條件判斷",
    "question": "某買方應備總供電容量100MW，已透過雙邊契約籌措40MW。若不考慮其他因素，依教材「不得超買」原則，其透過交易專區可再購買的上限最接近多少？",
    "option_a": "60MW",
    "option_b": "100MW",
    "option_c": "140MW",
    "option_d": "無上限",
    "answer": "A",
    "explanation": "買方購買量不得高於應備總量扣除已籌措備用供電容量後的餘額，因此100－40＝60MW。",
    "source_title": "09. 電力交易平台參考資料 備用容量交易機制",
    "source_url": "",
    "source_locator": "備用容量市場重要義務－買方不得超買",
    "verification": "B-rule+calculation",
    "is_active": true,
    "tags": "單元09;已核對;高鑑別;超買;雙邊契約;計算"
  }
]
);
