window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"H3-001","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜電能批發市場","level":"1基礎","question":"電能批發市場的主要目的為何？","option_a":"開放發電自由競爭並促進發電效率","option_b":"讓用戶自由選擇所有家電品牌","option_c":"只處理長期備用容量","option_d":"只處理輸電設備維修","answer":"A","explanation":"教材指出電能批發市場目的在開放發電自由競爭、促進發電效率。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"國外電力市場概要－電力市場架構","is_active":true,"tags":"單元03;電能批發市場"},
{"id":"H3-002","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜容量市場","level":"2理解","question":"容量市場較主要在處理哪一類問題？","option_a":"遠期電能容量、降低價格波動並鼓勵發電投資","option_b":"即時家用電器故障","option_c":"只決定零售電價","option_d":"只做頻率量測","answer":"A","explanation":"教材將容量市場定位為遠期容量交易，並提到減少價格波動、鼓勵發電端投資。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"國外電力市場概要－容量市場","is_active":true,"tags":"單元03;容量市場"},
{"id":"H3-003","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜輔助服務市場","level":"1基礎","question":"輔助服務市場的主要目的為何？","option_a":"確保電能、電壓與頻率的平衡及穩定","option_b":"增加所有用戶基本電費","option_c":"只處理售電帳務","option_d":"只處理燃料採購","answer":"A","explanation":"教材指出輔助服務市場是在即時調度前，確保系統電能、電壓與頻率平衡穩定。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"國外電力市場概要－輔助服務市場","is_active":true,"tags":"單元03;輔助服務市場"},
{"id":"H3-004","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜零售市場","level":"1基礎","question":"零售市場在教材中的主要目的為何？","option_a":"開放用戶自由選擇電力來源","option_b":"讓輸電業決定所有發電計畫","option_c":"只交易備用容量","option_d":"只做頻率調整","answer":"A","explanation":"教材將零售市場目的說明為開放用戶自由選擇電力來源。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"國外電力市場概要－零售市場","is_active":true,"tags":"單元03;零售市場"},
{"id":"H3-005","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜日前市場","level":"2理解","question":"「日前市場」最接近下列哪一項描述？","option_a":"在調度日前進行電力交易，以滿足調度日供需","option_b":"只在事故後才開啟","option_c":"只交易十年後容量","option_d":"只提供用戶帳單查詢","answer":"A","explanation":"教材將日前市場描述為調度日前之電力交易，用以滿足調度日電力供需。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"國內電力市場未來架構","is_active":true,"tags":"單元03;日前市場"},
{"id":"H3-006","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜即時市場","level":"2理解","question":"「即時市場」的主要功能最接近哪一項？","option_a":"調度日即時電能交易，滿足即時調度需求","option_b":"只交易多年後發電容量","option_c":"只做年度財務結算","option_d":"只處理電網設備採購","answer":"A","explanation":"教材將即時市場定位為調度日之即時電能交易，以滿足即時調度需求。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"國內電力市場未來架構","is_active":true,"tags":"單元03;即時市場"},
{"id":"H3-007","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜平台市場架構","level":"1基礎","question":"依電力交易平台設置規則，平台現階段主要分為哪兩個市場？","option_a":"日前輔助服務市場與備用容量市場","option_b":"股票市場與期貨市場","option_c":"燃料市場與零售市場","option_d":"輸電市場與配電市場","answer":"A","explanation":"教材引用設置規則，電力交易平台分為日前輔助服務市場及備用容量市場。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力交易平台設置規則－第3條","is_active":true,"tags":"單元03;平台架構"},
{"id":"H3-008","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜管理規範","level":"2理解","question":"依教材引用之設置規則，輸配電業原則上至少多久應檢討一次管理規範及作業程序？","option_a":"每半年","option_b":"每一年","option_c":"每二年","option_d":"每五年","answer":"C","explanation":"教材引用第15條，除主管機關另有指示外，輸配電業應至少每二年檢討一次。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力交易平台設置規則－第15條","is_active":true,"tags":"單元03;管理規範"}
]);