window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"H2-001","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜負載預測","level":"2理解","question":"下列何者較屬於短期系統負載的影響因素？","option_a":"人口與產業結構","option_b":"所得與家電普及率","option_c":"氣溫與特殊節日","option_d":"長期經濟結構","answer":"C","explanation":"教材將氣溫、特殊節日、生活習慣及生產活動列為短期影響因素。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"影響系統負載因素","is_active":true,"tags":"單元02;負載預測"},
{"id":"H2-002","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜負載特性","level":"1基礎","question":"依教材，台灣一般日負載曲線常見的型態為何？","option_a":"白天及夜間雙尖峰，深夜最低","option_b":"只有清晨一個尖峰","option_c":"全天完全平坦","option_d":"中午最低、深夜最高","answer":"A","explanation":"教材指出白天及夜尖峰為最高，深夜最低，呈現雙尖峰特性。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"台灣電力系統負載特性","is_active":true,"tags":"單元02;負載曲線"},
{"id":"H2-003","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜電源調度","level":"2理解","question":"電源調度的主要目標，下列何者最符合教材？","option_a":"只追求最大發電量","option_b":"供應隨時變化的負載、維持電力品質並使整體電力成本最小化","option_c":"只降低輸電線數量","option_d":"固定所有機組全天滿載","answer":"B","explanation":"教材強調供應變動負載、維持良好電力品質，同時使整體電力成本最小化。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"電源調度之任務","is_active":true,"tags":"單元02;電源調度"},
{"id":"H2-004","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜機組調度","level":"2理解","question":"哪一類機組的典型特性是一天中可數次啟停，且反應速度較快？","option_a":"基載機組","option_b":"中載機組","option_c":"尖載機組","option_d":"長期備用容量","answer":"C","explanation":"教材將燃油、水力、燃氣等可較快速啟停的機組歸為尖載機組。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"滿足負載的機組調度原則","is_active":true,"tags":"單元02;機組調度"},
{"id":"H2-005","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜抽蓄水力","level":"2理解","question":"下列何者是抽蓄水力對系統的重要貢獻？","option_a":"只在尖峰時抽水","option_b":"可填谷削峰，並提供調頻、快速備轉與補充備轉","option_c":"只能提供長期容量規劃","option_d":"不能參與任何調度","answer":"B","explanation":"抽蓄水力可於低負載時抽水、尖峰時發電，並支援調頻及多種備轉服務。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"抽蓄水力對系統之貢獻","is_active":true,"tags":"單元02;抽蓄水力"},
{"id":"H2-006","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜再生能源調度","level":"2情境","question":"太陽光電占比提高後，教材所稱的「鴨子曲線」更明顯，代表什麼？","option_a":"電網調度壓力可能增加","option_b":"全天負載完全不變","option_c":"所有火力機組都可停機","option_d":"不再需要備轉容量","answer":"A","explanation":"太陽光電受氣候與晝夜影響，佔比提高會使鴨子曲線更明顯，增加系統調度壓力。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"再生能源大量併網－太陽光電","is_active":true,"tags":"單元02;鴨子曲線;再生能源"},
{"id":"H2-007","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜共同最佳化","level":"2理解","question":"電力市場的共同最佳化（Co-Optimize）在教材中的主要目標函數為何？","option_a":"最大化全系統發電成本","option_b":"最小化全系統發電成本","option_c":"最大化所有機組啟停次數","option_d":"固定市場價格","answer":"B","explanation":"教材列示共同最佳化的目標函數為Min{全系統發電成本}。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"電力市場之共同最佳化","is_active":true,"tags":"單元02;共同最佳化"},
{"id":"H2-008","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜短期負載預測","level":"2理解","question":"教材所述短期負載預測，會綜合哪些資料？","option_a":"未來7日天氣預報、歷史負載與特殊節日等","option_b":"只看昨天總用電量","option_c":"只看發電機組數量","option_d":"只看年度GDP","answer":"A","explanation":"教材說明會利用未來7日天氣預報、過去負載型態、節日及溫濕度與負載關聯等資料進行預測。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"短期負載預測方法","is_active":true,"tags":"單元02;短期負載預測"}
]);