window.LOCAL_QUESTIONS=(window.LOCAL_QUESTIONS||[]).concat([
{"id":"V01-001","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜電力系統架構","level":"1基礎","question":"電力系統的主要環節依序最接近下列何者？","option_a":"發電、輸電、配電、售電／用電服務","option_b":"發電、金融、保險、零售","option_c":"輸電、發電、銀行、售電","option_d":"配電、農業、輸電、發電","answer":"A","explanation":"教材將電力系統由發電、輸電、配電到售電／用電端加以說明。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"壹、電力系統架構","is_active":true,"tags":"單元01;已核對;基礎"},
{"id":"V01-002","subject":"科目一｜電力系統與電力市場","topic":"第1單元｜可靠度指標","level":"1基礎","question":"哪一項指標較偏向衡量遠期發電端供電可靠度？","option_a":"備用容量率","option_b":"備轉容量率","option_c":"每秒頻率變化率","option_d":"線路損失率","answer":"A","explanation":"教材明列備用容量（率）衡量遠期發電端供電可靠度；備轉容量（率）衡量短期實際可調度裕度。","source_title":"01. 電力交易平台參考資料 台灣電力系統概論","source_url":"","source_locator":"電源結構－可靠度指標","is_active":true,"tags":"單元01;已核對;備用容量;備轉容量"},
{"id":"V02-001","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜電力調度","level":"1基礎","question":"因電力無法大量儲存，系統運轉時發電量應如何配合？","option_a":"隨負載變化調整，以維持供需平衡","option_b":"固定不變","option_c":"只在月底調整一次","option_d":"只依電價調整，與負載無關","answer":"A","explanation":"教材指出電力無法大量儲存，發電量必須隨負載變化，維持每分每秒供需平衡。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"壹、電力調度之任務","is_active":true,"tags":"單元02;已核對;基礎"},
{"id":"V02-002","subject":"科目一｜電力系統與電力市場","topic":"第2單元｜調度分工","level":"1基礎","question":"下列何者較屬於電網調度的主要任務？","option_a":"電壓調整、輸電網路操作與潮流監控","option_b":"只決定年度燃料採購","option_c":"只計算用戶電費","option_d":"只管理市場保證金","answer":"A","explanation":"教材結語將電網調度重點列為電壓調整、輸電網路操作及電力潮流監控。","source_title":"02. 電力交易平台參考資料 電力系統運轉與調度","source_url":"","source_locator":"伍、結語","is_active":true,"tags":"單元02;已核對;電網調度"},
{"id":"V03-001","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜平台市場架構","level":"1基礎","question":"電力交易平台主要分為哪兩個市場？","option_a":"日前輔助服務市場與備用容量市場","option_b":"股票市場與期貨市場","option_c":"碳權市場與保險市場","option_d":"零售市場與外匯市場","answer":"A","explanation":"教材將國內電力交易平台分為日前輔助服務市場與備用容量市場。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"參、國內電力市場規劃／電力交易平台設置規則","is_active":true,"tags":"單元03;已核對;市場架構"},
{"id":"V03-002","subject":"科目一｜電力系統與電力市場","topic":"第3單元｜市場類型","level":"1基礎","question":"哪一類市場主要與維持電能、電壓、頻率平衡與穩定有關？","option_a":"輔助服務市場","option_b":"零售市場","option_c":"一般商品市場","option_d":"保險市場","answer":"A","explanation":"輔助服務市場重點在維持系統穩定與即時平衡。","source_title":"03. 電力交易平台參考資料 電力交易市場概述","source_url":"","source_locator":"電力市場架構－輔助服務市場","is_active":true,"tags":"單元03;已核對;輔助服務市場"},
{"id":"V04-001","subject":"科目一｜電力系統與電力市場","topic":"第4單元｜反應時間","level":"1基礎","question":"下列哪一組反應時間配對正確？","option_a":"dReg≤1秒、sReg≤10秒、即時備轉≤10分鐘、補充備轉≤30分鐘","option_b":"dReg≤10分鐘、sReg≤30分鐘、即時備轉≤1秒、補充備轉≤10秒","option_c":"四者皆≤1秒","option_d":"四者皆≤30分鐘","answer":"A","explanation":"教材商品表明列dReg 1秒、sReg 10秒、即時備轉10分鐘、補充備轉30分鐘。","source_title":"04. 電力交易平台參考資料 輔助服務概論","source_url":"","source_locator":"參、國內輔助服務介紹－我國輔助服務項目分類","is_active":true,"tags":"單元04;已核對;反應時間"},
{"id":"V05-001","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜保證金","level":"1基礎","question":"合格交易者保證金不足時，原則上應於收到通知之次日起多久內補足？","option_a":"5個工作日","option_b":"10個工作日","option_c":"30日","option_d":"180日","answer":"A","explanation":"管理規範第十條規定，保證金不足應於通知次日起五個工作日內補足。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第十條【保證金規範】","is_active":true,"tags":"單元05;已核對;5個工作日;保證金"},
{"id":"V05-002","subject":"科目二｜電力交易平台市場規則","topic":"第5單元｜爭議處理","level":"1基礎","question":"電力交易爭議經電力交易單位溝通協商仍未解決時，下一步依教材為何？","option_a":"由學者專家協調會進行協調","option_b":"自動判定賣方勝訴","option_c":"立即永久停權","option_d":"不再處理","answer":"A","explanation":"教材第三十五條規定，先由電力交易單位溝通協商，未解決則由學者專家協調會協調。","source_title":"05. 電力交易平台參考資料 電力交易平台管理規範及作業程序總覽","source_url":"","source_locator":"第三十五條【學者專家協調會之協調原則】","is_active":true,"tags":"單元05;已核對;爭議處理"},
{"id":"V06-001","subject":"科目二｜電力交易平台市場規則","topic":"第6單元｜專業人員資格證明","level":"1基礎","question":"申請成為合格交易者時，自有資源模式與代理資源模式所需專業人員資格證明最低張數分別為何？","option_a":"1張、3張","option_b":"3張、1張","option_c":"1張、1張","option_d":"3張、3張","answer":"A","explanation":"教材列示採自有資源參與者1張，採代理資源參與者3張。","source_title":"06. 電力交易平台參考資料 日前輔助服務市場之參與作法","source_url":"","source_locator":"電力交易平台專業人員資格證明","is_active":true,"tags":"單元06;已核對;專業人員"},
{"id":"V07-001","subject":"科目二｜電力交易平台市場規則","topic":"第7單元｜E-dReg儲能規格","level":"1基礎","question":"併網型儲能參與E-dReg時，參與容量與儲能電能量最低門檻分別為何？","option_a":"1MW與2.5MWh","option_b":"0.1MW與0.5MWh","option_c":"10MW與10MWh","option_d":"沒有最低門檻","answer":"A","explanation":"教材規定E-dReg參與容量及儲能電能量分別不低於1MW與2.5MWh。","source_title":"07. 電力交易平台參考資料 日前輔助服務市場之交易商品項目規格","source_url":"","source_locator":"併網型儲能設備參與E-dReg","is_active":true,"tags":"單元07;已核對;E-dReg;1MW;2.5MWh"},
{"id":"V08-001","subject":"科目二｜電力交易平台市場規則","topic":"第8單元｜市場時程","level":"1基礎","question":"日前輔助服務市場每日報價截止與公布競價結果的時點分別為何？","option_a":"11時截止、16時公布","option_b":"16時截止、11時公布","option_c":"9時截止、12時公布","option_d":"沒有固定時點","answer":"A","explanation":"教材結語明列每日11時截止報價，16時公布競價結果。","source_title":"08. 電力交易平台參考資料 日前輔助服務市場之運作","source_url":"","source_locator":"柒、結語","is_active":true,"tags":"單元08;已核對;11時;16時"},
{"id":"V09-001","subject":"科目二｜電力交易平台市場規則","topic":"第9單元｜交易容量","level":"1基礎","question":"備用容量市場賣方交易資源的交易容量基本規則，下列何者正確？","option_a":"須達10kW（含）以上，基本單位10kW，且不得聚合","option_b":"至少1MW且可任意聚合","option_c":"沒有最低容量也可聚合","option_d":"至少100MW","answer":"A","explanation":"教材明列交易容量按淨尖峰能力計算，須10kW（含）以上，基本單位10kW，且不得聚合。","source_title":"09. 電力交易平台參考資料 備用容量交易機制","source_url":"","source_locator":"備用容量市場供給者之參與方式","is_active":true,"tags":"單元09;已核對;10kW;不得聚合"},
{"id":"V10-001","subject":"科目一｜電力系統與電力市場","topic":"第10單元｜SD-WAN","level":"1基礎","question":"教材提到電力交易平台使用哪一項通訊技術，可自動偵測通訊品質並調整通訊路徑？","option_a":"SD-WAN","option_b":"紙本傳真","option_c":"一般電話語音","option_d":"傳統郵件","answer":"A","explanation":"教材指出平台使用SD-WAN與合格交易者傳遞訊息，具自動偵測通訊品質與調整通訊路徑功能。","source_title":"10. 我國電力交易市場推動之方向與展望","source_url":"","source_locator":"貳、電力交易平台創新技術應用－運用數位科技整合全國電力資源","is_active":true,"tags":"單元10;已核對;SD-WAN"}
]);
